exclude_paths:
  - "coverity_model.cc"
  - "deprecated/**"
  - "gui/coretool/gpsbabel_*.ts"
  - "gui/gpsbabelfe_*.ts"
  - "jeeps/gpsproj.cc"
  - "jeeps/gpsproj.h"
  - "mac/libusb/**"
  - "reference/**"
  - "shapelib/**"
  - "strptime/**"
  - "tools/qtci/README.md"
  - "tools/uploadtool/README.md"
  - "zlib/**"
