exclude_paths:
  - 'deprecated/**'
  - 'mac/libusb/**'
  - 'reference/**'
  - 'shapelib/**'
  - 'zlib/**'
  - coverity_model.cc
  - height.cc # It takes newer cppcheck versions, somewhere > 1.82, an excessive amount of time to analyze heightgrid.h
  - strptime.[ch]
  - jeeps/gpsproj.cc
  - jeeps/gpsproj.h
