exclude_paths:
  - 'deprecated/**'
  - 'mac/libusb/**'
  - 'reference/**'
  - 'shapelib/**'
  - 'zlib/**'
  - coverity_model.cc
  - strptime.[ch]
  - jeeps/gpsproj.cc
  - jeeps/gpsproj.h
  - tools/qtci/README.md
  - tools/uploadtool/README.md
