# CMake generated Testfile for 
# Source directory: /Users/robertlipe/src/gpsbabel
# Build directory: /Users/robertlipe/src/gpsbabel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-arc "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "arc")
set_tests_properties(test-arc PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-arc-project "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "arc-project")
set_tests_properties(test-arc-project PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-batch "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "batch")
set_tests_properties(test-batch PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-bend "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "bend")
set_tests_properties(test-bend PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-classic-2 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "classic-2")
set_tests_properties(test-classic-2 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-classic-3 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "classic-3")
set_tests_properties(test-classic-3 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-dg100 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "dg100")
set_tests_properties(test-dg100 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-dop_filter "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "dop_filter")
set_tests_properties(test-dop_filter PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-duplicate "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "duplicate")
set_tests_properties(test-duplicate PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-exif "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "exif")
set_tests_properties(test-exif PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-garmin_fit "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "garmin_fit")
set_tests_properties(test-garmin_fit PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-garmin_g1000 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "garmin_g1000")
set_tests_properties(test-garmin_g1000 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-garmin_gpi "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "garmin_gpi")
set_tests_properties(test-garmin_gpi PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-garmin_txt "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "garmin_txt")
set_tests_properties(test-garmin_txt PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-garmin_xt "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "garmin_xt")
set_tests_properties(test-garmin_xt PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gbfile "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gbfile")
set_tests_properties(test-gbfile PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gdb "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gdb")
set_tests_properties(test-gdb PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-geo "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "geo")
set_tests_properties(test-geo PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-geojson "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "geojson")
set_tests_properties(test-geojson PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-globalsat_sport "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "globalsat_sport")
set_tests_properties(test-globalsat_sport PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gpsdrive "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gpsdrive")
set_tests_properties(test-gpsdrive PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gpssim "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gpssim")
set_tests_properties(test-gpssim PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gpx "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gpx")
set_tests_properties(test-gpx PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-grapheme "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "grapheme")
set_tests_properties(test-grapheme PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gtm "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gtm")
set_tests_properties(test-gtm PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-gtrnctr "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "gtrnctr")
set_tests_properties(test-gtrnctr PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-height "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "height")
set_tests_properties(test-height PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-holux "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "holux")
set_tests_properties(test-holux PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-humminbird "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "humminbird")
set_tests_properties(test-humminbird PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-iblue747 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "iblue747")
set_tests_properties(test-iblue747 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-igc "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "igc")
set_tests_properties(test-igc PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-interpolate "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "interpolate")
set_tests_properties(test-interpolate PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-kml "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "kml")
set_tests_properties(test-kml PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-kml-read "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "kml-read")
set_tests_properties(test-kml-read PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-lowranceusr "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "lowranceusr")
set_tests_properties(test-lowranceusr PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-mtk "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "mtk")
set_tests_properties(test-mtk PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-multiurlgpx "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "multiurlgpx")
set_tests_properties(test-multiurlgpx PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-navilink "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "navilink")
set_tests_properties(test-navilink PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-nmea "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "nmea")
set_tests_properties(test-nmea PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-osm "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "osm")
set_tests_properties(test-osm PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-ozi "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "ozi")
set_tests_properties(test-ozi PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-polygon "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "polygon")
set_tests_properties(test-polygon PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-position "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "position")
set_tests_properties(test-position PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-qstarz_bl_1000 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "qstarz_bl_1000")
set_tests_properties(test-qstarz_bl_1000 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-radius "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "radius")
set_tests_properties(test-radius PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-realtime "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "realtime")
set_tests_properties(test-realtime PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-resample "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "resample")
set_tests_properties(test-resample PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-route_reverse "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "route_reverse")
set_tests_properties(test-route_reverse PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-sbn "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "sbn")
set_tests_properties(test-sbn PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-sbp "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "sbp")
set_tests_properties(test-sbp PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-serialization "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "serialization")
set_tests_properties(test-serialization PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-shape "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "shape")
set_tests_properties(test-shape PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-simplify "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "simplify")
set_tests_properties(test-simplify PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-simplify-relative "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "simplify-relative")
set_tests_properties(test-simplify-relative PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-skytraq "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "skytraq")
set_tests_properties(test-skytraq PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-sort "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "sort")
set_tests_properties(test-sort PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-stackfilter "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "stackfilter")
set_tests_properties(test-stackfilter PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-subrip "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "subrip")
set_tests_properties(test-subrip PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-swap "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "swap")
set_tests_properties(test-swap PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-text "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "text")
set_tests_properties(test-text PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-tpg "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "tpg")
set_tests_properties(test-tpg PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-tpo "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "tpo")
set_tests_properties(test-tpo PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-track "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "track")
set_tests_properties(test-track PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-track-discard "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "track-discard")
set_tests_properties(test-track-discard PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-transform "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "transform")
set_tests_properties(test-transform PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-unicsv "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "unicsv")
set_tests_properties(test-unicsv PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-unicsv_grids "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "unicsv_grids")
set_tests_properties(test-unicsv_grids PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-unitconversion "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "unitconversion")
set_tests_properties(test-unitconversion PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-v900 "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "v900")
set_tests_properties(test-v900 PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-validate "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "validate")
set_tests_properties(test-validate PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-validate_formats "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "validate_formats")
set_tests_properties(test-validate_formats PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-vcard "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "vcard")
set_tests_properties(test-vcard PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
add_test(test-xcsv "/Users/robertlipe/src/gpsbabel/testo" "-p" "/Users/robertlipe/src/gpsbabel/gpsbabel" "xcsv")
set_tests_properties(test-xcsv PROPERTIES  WORKING_DIRECTORY "/Users/robertlipe/src/gpsbabel" _BACKTRACE_TRIPLES "/Users/robertlipe/src/gpsbabel/CMakeLists.txt;460;add_test;/Users/robertlipe/src/gpsbabel/CMakeLists.txt;0;")
subdirs("gui")
