#!/bin/sh
#  $Id: gpsbabelfe,v 1.2 2009-09-14 14:25:14 robertl Exp $
#  Copyright (C) 2009  S. Khai Mong <khai@mangrai.com>.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111
#  USA
#


FollowSymLinks()
{
    fullpath="$1"
    while [ -L "$fullpath" ]; do
	pathdir=`dirname "$fullpath"`
        linktarget=`/bin/ls -l "$fullpath" | sed -e 's/.* -> //'`
	d1=`dirname "$linktarget"`
 	linkdir=`cd "$pathdir" && cd "$d1" && pwd`
	linkfile=`basename "$linktarget"`
	fullpath=$linkdir/$linkfile
    done
    echo $fullpath
}

finalpath=`FollowSymLinks "$0"`
LD_LIBRARY_PATH=`dirname "$finalpath"`:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

if [ -x "${finalpath}-bin" ]; then
    #ldd "${finalpath}-bin"
    exec "${finalpath}-bin"  "$@"
fi
echo "Couldn't find/run gpsbabelfe-bin.  Possible installation issues"
exit 1

