/* This file is machine-generated from the contents of style/ */
/* by mkstyle.sh.   Editing it by hand is an exeedingly bad idea. */

#include "defs.h"
#if CSVFMTS_ENABLED
static char arc[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: GPSBabel arc filter format\n"
"# Author: Ron Parker\n"
"#   Date: 17 July 2003\n"
"#\n"

"DESCRIPTION		GPSBabel arc filter file\n"
"EXTENSION		txt\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LAT_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD	LON_HUMAN_READABLE, \"\", \"%08.5f\"\n"

"OFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
;
static char cambridge[] = 
"DESCRIPTION     Cambridge/Winpilot glider software\n"
"SHORTLEN        8\n"
"EXTENSION dat\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER         COMMA\n"
"RECORD_DELIMITER        NEWLINE\n"
"BADCHARS                COMMA\n"

"IFIELD INDEX,\"1\",\"%d\"\n"
"IFIELD LAT_HUMAN_READABLE,\"\",\"%d:%06.3f%c\"\n"
"IFIELD LON_HUMAN_READABLE,\"\",\"%03d:%06.3f%c\"\n"
"IFIELD ALT_METERS,\"\",\"%3.0fM\"\n"
"IFIELD CONSTANT,\"\",\"T\"\n"
"IFIELD SHORTNAME,\"\",\"%s\"\n"
"IFIELD DESCRIPTION,\"\",\"%s\"\n"
;
static char csv[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: DeLorme SA 9.0 CSV\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"DESCRIPTION	Comma separated values\n"
"SHORTLEN	8\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMASPACE\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LAT_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD	LON_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"

"OFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	DESCRIPTION, \"\", \"%s\"\n"
;
static char cup[] = 
"#\n"
"# (c) 2006, Robert Lipe, based on  sample files by Krzysztof Wojtas\n"
"# Reference info: http://www.seeyou.ws/thankyou.php?fname=cup_format.pdf\n"
"#\n"

"DESCRIPTION      See You flight analysis data\n"
"SHORTLEN  8\n"
"EXTENSION cup\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER         COMMA\n"
"RECORD_DELIMITER        NEWLINE\n"
"BADCHARS                ,\"\n"
"PROLOGUE name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc\n"
"EPILOGUE -----Related Tasks-----\n"


"IFIELD SHORTNAME,\"\", \"\"%s\"\"\n"
"IFIELD SHORTNAME,\"\", \"%s\"\n"
"IFIELD CONSTANT,\"\", \"\"\n"
"IFIELD LAT_DDMMDIR, \"%f\", \"%08.3f\", \"absolute\"\n"
"IFIELD LON_DDMMDIR, \"%f\", \"%09.3f\", \"absolute\"\n"
"IFIELD ALT_METERS,\"\", \"%dm\"\n"
"IFIELD CONSTANT,\"\", \"1\"\n"
"IFIELD CONSTANT,\"\", \"\"\n"
"IFIELD CONSTANT,\"\", \"\"\n"
"IFIELD CONSTANT,\"\", \"\"\n"
"IFIELD DESCRIPTION,\"\", \"\"%s\"\"\n"

"OFIELD SHORTNAME,\"\", \"\"%s\"\"\n"
"OFIELD SHORTNAME,\"\", \"%s\"\n"
"OFIELD CONSTANT,\"\", \"\"\n"
"OFIELD LAT_DDMMDIR, \"\", \"%08.3f%c\"\n"
"OFIELD LON_DDMMDIR, \"\", \"%09.3f%c\"\n"
"OFIELD ALT_METERS,\"\", \"%3.1fm\"\n"
"OFIELD CONSTANT,\"\", \"1\"\n"
"OFIELD CONSTANT,\"\", \"\"\n"
"OFIELD CONSTANT,\"\", \"\"\n"
"OFIELD CONSTANT,\"\", \"\"\n"
"OFIELD DESCRIPTION,\"\", \"\"%s\"\"\n"


;
static char custom[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Custom \"Everything\" Style\n"
"# Author: Alex Mottram\n"
"#   Date: 11/24/2002\n"
"#\n"
"#\n"

"DESCRIPTION		Custom \"Everything\" Style\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"
"FORMAT_TYPE		INTERNAL\n"

"#\n"
"# HEADER STUFF:\n"
"#\n"
"PROLOGUE	Prologue Line 1 __FILE__\n"
"PROLOGUE	Prologue Line 2\n"

"#\n"
"# INDIVIDUAL DATA FIELDS:\n"
"#\n"
"IFIELD	CONSTANT, \"CONSTANT\", \"%s\"\n"
"IFIELD	INDEX, \"\", \"%d\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LAT_DIR, \"\", \"%c\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LON_DIR, \"\", \"%c\"\n"
"IFIELD	ICON_DESCR, \"\", \"%s\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	NOTES, \"\", \"%s\"\n"
"IFIELD	URL, \"\", \"%s\" 		\n"
"IFIELD	URL_LINK_TEXT, \"\", \"%s\"\n"
"IFIELD	ALT_METERS, \"\", \"%fM\"\n"
"IFIELD	ALT_FEET, \"\", \"%fF\"\n"
"IFIELD	LAT_DECIMALDIR, \"\", \"%f/%c\"\n"
"IFIELD	LON_DECIMALDIR, \"\", \"%f/%c\"\n"
"IFIELD	LAT_DIRDECIMAL, \"\", \"%c/%f\"\n"
"IFIELD	LON_DIRDECIMAL, \"\", \"%c/%f\"\n"
"IFIELD	LAT_INT32DEG, \"\", \"%ld\"\n"
"IFIELD	LON_INT32DEG, \"\", \"%ld\"\n"
"IFIELD	TIMET_TIME, \"\", \"%ld\"\n"
"IFIELD	EXCEL_TIME, \"\", \"%f\"\n"

"# EPILOGUE: \n"
"EPILOGUE	Epilogue Line 1\n"
"EPILOGUE	Epilogue Line 2\n"
;
static char dna[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: DNA Marker Format\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"# As defined in dna.c\n"
"#\n"
"#\n"

"DESCRIPTION 		Navitrak DNA marker format\n"
"EXTENSION		dna\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	INDEX, \"\", \"%d\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"

;
static char flysight[] = 
"# Format:	FlySight\n"
"# Author:	LukeH\n"
"# Date:		10/10/10\n"

"DESCRIPTION		FlySight GPS File\n"
"EXTENSION		csv\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"FIELD_DELIMITER COMMA\n"
"RECORD_DELIMITER NEWLINE\n"
"BADCHARS ,\"\n"

"PROLOGUE time lat lon hMSL velN velE velD hAcc vAcc sAcc gpsFix numSV\n"
"PROLOGUE\n"

"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"IFIELD ISO_TIME,	\"\",	\"%s\"	# Date & time\n"
"IFIELD LAT_DECIMAL,	\"\",	\"%f\"	# Latitude\n"
"IFIELD LON_DECIMAL,	\"\",	\"%f\"	# Longitude\n"
"IFIELD ALT_METERS,	\"\",	\"%.0f\"	# Altitude above MSL (m)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Velocity north (m/s)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Velocity east (m/s)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Velocity down (m/s)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Horizontal accuracy (m)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Vertical accuracy (m)\n"
"IFIELD IGNORE,		\"\",	\"%s\"	# Speed accuracy (m/s)\n"
"IFIELD GPS_FIX,		\"\",	\"%s\"	# GPS fix type\n"
"IFIELD GPS_SAT,		\"\",	\"%d\"	# Number of satellites used in fix\n"
;
static char fugawi[] = 
"# fugawi XCSV style file\n"
"#\n"
"# Format: Fugawi\n"
"# Author: Robert Lipe, Patrick Ohly\n"
"#   Date: 07/24/2005\n"
"#\n"
"# \n"

"DESCRIPTION		Fugawi\n"
"EXTENSION		txt\n"
"SHORTLEN		10\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"

"PROLOGUE \\# Latitude, Longitude and UTM coordinates are in WGS84 datum\n"
"PROLOGUE \\#\n"
"PROLOGUE \\# Every set of data contains the following:\n"
"PROLOGUE \\#\n"
"PROLOGUE \\# Waypoint name\n"
"PROLOGUE \\# Waypoint comment\n"
"PROLOGUE \\# Waypoint description\n"
"PROLOGUE \\# Latitude in Degree and decimals (soutern hemisphere has neg. degrees)\n"
"PROLOGUE \\# Longitude in degree and decimals (neg. numbers: west of Greenwich)\n"
"PROLOGUE \\# Height in meters [optional when importing, always present when exporting: Date (GMT) as ISO YYYYMMDD, Time of the day relative to the date as HHMMSS\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	NOTES, \"\", \"%s\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%-.7f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%-.7f\"\n"
"IFIELD	ALT_METERS, \"\", \"%-7.1f\"\n"
"IFIELD  GMT_TIME, \"\", \"%Y%m%d\"\n"
"IFIELD  HMSG_TIME, \"\", \"%02d%02d%02d\"\n"
;
static char garmin301[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Garmin 301 Position + Heartrate data\n"
"# Author: Jeff Kalikstein\n"
"#   Date: 08/29/2005\n"
"#\n"

"DESCRIPTION		Garmin 301 Custom position and heartrate\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"
"#FORMAT_TYPE		INTERNAL\n"

"#\n"
"# HEADER STUFF:\n"
"#\n"
"PROLOGUE	Garmin 301 data __FILE__ \n"
"PROLOGUE	Timestamp,Latitude, Longitude, Altitude(ft), heart rate\n"
"#\n"
"# INDIVIDUAL DATA FIELDS:\n"
"#\n"
"IFIELD	TIMET_TIME,\"\",\"%ld\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"\n"
"IFIELD	ALT_FEET, \"\", \"%fF\"\n"
"IFIELD  HEART_RATE,\"\",\" %d\"	# beats per minute\n"


"# EPILOGUE: \n"
"#EPILOGUE	Epilogue Line 1\n"
"#EPILOGUE	Epilogue Line 2\n"
;
static char garmin_poi[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Garmin POI\n"
"# Author: Robert Lipe\n"
"# Date: 10/07/2005\n"
"# Reference: http://forums.groundspeak.com/GC/index.php?showtopic=110641&st=0&#entry1752204\n"
"#\n"
"DESCRIPTION Garmin POI database\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER COMMA\n"
"RECORD_DELIMITER NEWLINE\n"
"BADCHARS COMMA\n"
"SHORTLEN 24\n"
"# PROLOGUE Longitude,Latitude,Name, comment\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD LON_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD LAT_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD SHORTNAME, \"\", \"%s\"\n"
"IFIELD DESCRIPTION, \"\", \"%s\"\n"

"OFIELD LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD SHORTNAME, \"\", \"%-.24s\"\n"
"OFIELD GEOCACHE_TYPE, \"\", \" %-.4s\", \"no_delim_before,optional\"\n"
"OFIELD GEOCACHE_CONTAINER, \"\", \"/%-.4s \", \"no_delim_before,optional\"\n"
"OFIELD GEOCACHE_DIFF, \"\", \"(%3.1f\", \"no_delim_before,optional\"\n"
"OFIELD GEOCACHE_TERR, \"\", \"/%3.1f)\", \"no_delim_before,optional\"\n"
"OFIELD DESCRIPTION, \"\", \"%-.50s\"\n"
;
static char geonet[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: GEOnet Names Server (GNS) (http://earth-info.nga.mil/gns/html/cntry_files.html)\n"
"# Author: Olaf Klein\n"
"#   Date: 08/20/2002\n"
"#\n"

"DESCRIPTION		GEOnet Names Server (GNS)\n"
"EXTENSION		txt\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"

"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		TAB\n"
"ENCODING		UTF-8\n"

"PROLOGUE		RC	UFI	UNI	LAT	LONG	DMS_LAT	DMS_LONG	UTM	JOG	FC	DSG	PC	CC1	ADM1	ADM2	DIM	CC2	NT	LC	SHORT_FORM	GENERIC	SORT_NAME	FULL_NAME	FULL_NAME_ND	MODIFY_DATE\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	IGNORE, \"\", \"%s\"		# RC		( http://earth-info.nga.mil/gns/html/gis_contryfiles.html )\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UFI\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UNI\n"
"IFIELD	LAT_DECIMAL, \"\", \"%03.7f\"	# LAT\n"
"IFIELD	LON_DECIMAL, \"\", \"%03.7f\"	# LONG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DMS_LAT\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DMS_LONG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UTM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# JOG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# FC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DSG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# PC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# CC1\n"
"IFIELD	IGNORE, \"\", \"%s\"		# ADM1\n"
"IFIELD	IGNORE, \"\", \"%s\"		# ADM2\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DIM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# CC2\n"
"IFIELD	IGNORE, \"\", \"%s\"		# NT\n"
"IFIELD	IGNORE, \"\", \"%s\"		# LC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# SHORT_FORM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# GENERIC\n"
"IFIELD	SHORTNAME, \"\", \"%s\"		# SHORT_NAME\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"		# FULL_NAME\n"
"IFIELD	IGNORE, \"\", \"%s\"		# FULL_NAME_ND\n"
"IFIELD	IGNORE, \"\", \"%s\"		# MOD_DATE\n"
;
static char gpsdrive[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: GPSDrive\n"
"# Author: Alex Mottram\n"
"#   Date: 12/11/2002\n"
"#\n"
"# \n"
"#\n"

"DESCRIPTION		GpsDrive Format\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		WHITESPACE\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		,'\"\n"

"SHORTLEN          	20\n"
"SHORTWHITE              0\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"

"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	ICON_DESCR, \"\", \"%s\"\n"

"OFIELD	ANYNAME, \"\", \"%s\"\n"
"OFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	ICON_DESCR, \"\", \"%s\"\n"
;
static char gpsdrivetrack[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: GPSDriveTrack\n"
"# Author: Tobias Minich\n"
"#   Date: 12/07/2005\n"
"#\n"
"# \n"
"#\n"

"DESCRIPTION		GpsDrive Format for Tracks\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		WHITESPACE\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		,'\"\n"

"SHORTLEN          	20\n"
"SHORTWHITE              0\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"

"IFIELD	LAT_DECIMAL, \"\", \"%10.6f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%10.6f\"\n"
"IFIELD	ALT_METERS, \"\", \"%10.0f\"\n"
"# Reports are that this format stores in local time, not GMT as \n"
"# originally thought.\n"
"# IFIELD	GMT_TIME, \"\", \"%a %b %d %H:%M:%S %Y\"\n"
"IFIELD	LOCAL_TIME, \"\", \"%a %b %d %H:%M:%S %Y\"\n"
;
static char gpsman[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: GPSMAN Format\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"# As defined in gpsman.c\n"
"#\n"
"#\n"

"DESCRIPTION		GPSman\n"
"SHORTLEN		8\n"
"SHORTWHITE		0\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		TAB\n"

"PROLOGUE	!Format: DDD 1 WGS 84\n"
"PROLOGUE	!W:\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	SHORTNAME, \"\", \"%-8.8s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	LAT_DIRDECIMAL, \"\", \"%c%f\"\n"
"IFIELD	LON_DIRDECIMAL, \"\", \"%c%f\"\n"
"IFIELD	IGNORE, \"\", \"%s\"\n"

"# gpsman.c likes mkshort len = 8, whitespace = 0.\n"
;
static char iblue747[] = 
"# GPSBabel XCSV Style File http://www.gpsbabel.org/htmldoc-development/Styles.html\n"
"# Author: Christian Barmala http://www.barmala.de/\n"
"# License GNU Public License http://opensource.org/licenses/gpl-license.php\n"

"DESCRIPTION  Data Logger iBlue747 csv\n"
"EXTENSION csv\n"
"# full length csv with all options\n"

"# FILE LAYOUT DEFINITIIONS:\n"

"FIELD_DELIMITER COMMA\n"
"RECORD_DELIMITER NEWLINE\n"
"# BADCHARS COMMA\n"
"# SHORTLEN 16\n"
"# SHORTWHITE 0\n"
"# ENCODING UTF-8\n"
"DATATYPE TRACK\n"
"PROLOGUE INDEX,RCR,DATE,TIME,VALID,LATITUDE,N/S,LONGITUDE,E/W,HEIGHT,SPEED,PDOP,HDOP,VDOP,NSAT,DISTANCE,\n"


"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"

"IFIELD INDEX,\"1\",\"%d\"            # INDEX\n"
"IFIELD CONSTANT,\"T\",\"%s\"        # RCR\n"
"IFIELD GMT_TIME,\"\",\"%Y/%m/%d\"        # DATE\n"
"IFIELD HMSG_TIME,\"\",\"%02d:%02d:%02d\"    # TIME\n"
"IFIELD GPS_FIX,\"\",\"%s\"        # VALID #  No fix, SPS, DGPS, PPS\n"
"IFIELD LAT_DECIMAL,\"\",\"%f\"        # LATITUDE\n"
"IFIELD LAT_DIR,\"\",\"%c\"            # N/S\n"
"IFIELD LON_DECIMAL,\"\",\"%f\"        # LONGITUDE\n"
"IFIELD LON_DIR,\"\",\"%c\"            # E/W\n"
"IFIELD ALT_METERS,\"\",\"%.0f\"        # HEIGHT\n"
"IFIELD PATH_SPEED_KPH,\"\",\"%.1f\"        # SPEED\n"
"IFIELD IGNORE,\"\",\"%f\"        # HEADING\n"
"IFIELD IGNORE,\"\",\"%d\"        # DSTA\n"
"IFIELD IGNORE,\"\",\"%f\"        # DAGE\n"
"IFIELD GPS_PDOP,\"\",\"%f\"            # PDOP\n"
"IFIELD GPS_HDOP,\"\",\"%f\"            # HDOP\n"
"IFIELD GPS_VDOP,\"\",\"%f\"            # VDOP\n"
"IFIELD GPS_SAT,\"\",\"%d(\"            # NSAT USED/VIEW\n"
"IFIELD IGNORE,\"\",\"%s\"        # SAT INFO\n"
"IFIELD PATH_DISTANCE_KM,\"\",\"%f\"        # DISTANCE\n"
;
static char igo2008_poi[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: iGO2008 points of interest\n"
"# Author: Olaf Klein\n"
"#   Date: 09/05/2008\n"
"#\n"
"DESCRIPTION		iGO2008 points of interest (.upoi)\n"
"EXTENSION		upoi\n"
"DATATYPE		WAYPOINT\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		PIPE\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		\"|\n"
"ENCODING		MS-ANSI\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	INDEX,\"1\",\"%d\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	IGNORE, \"\", \"%s\"		# nothing\n"
"IFIELD	LAT_DECIMAL, \"\", \"%.6f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%.6f\"\n"
"IFIELD	IGNORE, \"\", \"%s\"		# Name of map\n"
"IFIELD	IGNORE, \"\", \"%s\"		# nothing\n"
"IFIELD	POSTAL_CODE, \"\", \"%s\"\n"
"IFIELD	CITY, \"\", \"%s\"\n"
"IFIELD	STREET_ADDR, \"\", \"%s\"		# Street without number\n"
"IFIELD	IGNORE, \"\", \"%s\"		# Street number\n"
"IFIELD	NOTES, \"\", \"%s\"\n"
"IFIELD	PHONE_NR, \"\", \"%s\"\n"
;
static char kompass_tk[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Kompass / Deutscher Alpenverein (DAV) Waypoints\n"
"# Author: Olaf Klein\n"
"#   Date: 01/10/2007\n"
"#\n"
"# \n"
"DESCRIPTION		Kompass (DAV) Track (.tk)\n"
"DATATYPE		TRACK\n"
"EXTENSION		wp\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		,\"\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LAT_DECIMAL, \"\", \"%.7f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%.7f\"\n"
;
static char kompass_wp[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Kompass / Deutscher Alpenverein (DAV) Waypoints\n"
"# Author: Olaf Klein\n"
"#   Date: 01/10/2007\n"
"#\n"
"# \n"
"DESCRIPTION		Kompass (DAV) Waypoints (.wp)\n"
"DATATYPE		WAYPOINT\n"
"EXTENSION		wp\n"
"ENCODING		UTF-8\n"
"FIELD_DELIMITER		SEMICOLON\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		,\"\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%.7f\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%.7f\"\n"
"IFIELD	ALT_METERS, \"\", \"%.0f\"\n"
"IFIELD	LOCAL_TIME,\"\",\"%d.%m.%Y %H:%M:%S\"\n"
"IFIELD	CONSTANT, \"Icons\\Wegpunkt grÃ¼n.bmp\", \"%s\"\n"
"IFIELD	IGNORE, \"\", \"%s\"\n"
"IFIELD  CONSTANT, \"1\", \"%s\"			# unknown\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
;
static char ktf2[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Kartex KTF 2.0 Degrees with decimals\n"
"# Author: Harald Nordius\n"
"#   Date: 4/13 2006\n"
"#\n"
"# \n"
"DESCRIPTION	Kartex 5 Track File\n"
"EXTENSION	ktf\n"
"DATATYPE	TRACK\n"
"SHORTLEN	10\n"
"SHORTWHITE	1\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"#\n"
"#\n"
"# FILE HEADER\n"
"#\n"
"PROLOGUE //Kartex Track File created by GPSBabel\n"
"PROLOGUE &KTF 2.0,sweref 99 lat long,0\n"
"#\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	CONSTANT, %, \"%s\"\n"
"IFIELD	INDEX, \"\", \"%d\"\n"
"IFIELD	LATLON_HUMAN_READABLE, \"\", \"%c%f°\"\n"
"IFIELD	ALT_METERS, \"\", \"%.2f\"\n"
"IFIELD	GMT_TIME, \"\", \"%Y-%m-%d %H:%M:%S\"\n"
"IFIELD	IGNORE, \"\", \"%s\" #Empty field\n"
"IFIELD	IGNORE, \"\", \"%s\" #Empty field\n"
"IFIELD	CONSTANT, \"$\", \"%s\"\n"
;
static char kwf2[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Kartex KWF 2.0 Degrees with decimals\n"
"# Author: Harald Nordius\n"
"#   Date: 12/08 2004\n"
"#\n"
"# \n"
"DESCRIPTION	Kartex 5 Waypoint File\n"
"EXTENSION	kwf\n"
"SHORTLEN	10\n"
"SHORTWHITE	1\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"ENCODING		CP1252\n"
"#\n"
"#\n"
"# FILE HEADER\n"
"#\n"
"PROLOGUE //Kartex Waypoint File created by GPSBabel\n"
"PROLOGUE &KWF 2.0,sweref 99 lat long,0\n"
"#\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	CONSTANT, \\#, \"%s\"\n"
"IFIELD	INDEX,\"\",\"%d\"\n"
"IFIELD	SHORTNAME,\"\",\"%s\"\n"
"IFIELD	LATLON_HUMAN_READABLE,\"\",\"%c%f°\"\n"
"IFIELD	ALT_METERS,\"\",\"%.2f\"\n"
"IFIELD	IGNORE, \"\",\"%s\" #Empty field\n"
"IFIELD	IGNORE, \"\",\"%s\" #Empty field\n"
"IFIELD	CONSTANT, \"0\",\"%s\" #Waypoint symbol code\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	CONSTANT, \"$\", \"%s\"\n"
;
static char mapconverter[] = 
"# Format: Mapopolis.com Mapconverter\n"
"# Author: Gary Paulson\n"
"#   Date: 01/13/2003\n"
"# Requires unsupported mapconverter.exe from mapopolis.com.\n"
"#\n"
"# Modifications by Alex Mottram documented 6/30/2003\n"
"# Change %-40.40s on description output to %-.40s to stop padding.\n"
"# Add QUOTE as badchars, remove COMMA.\n"
"# Removed Mapconverter.exe's README information from style file.\n"
"# Changed OFIELD to IFIELD in case you ever want to read one of these things.\n"
"#\n"
"#\n"
"DESCRIPTION		Mapopolis.com Mapconverter CSV\n"
"EXTENSION		txt\n"

"# FILE LAYOUT DEFINITIIONS:\n"

"FIELD_DELIMITER   COMMASPACE\n"
"RECORD_DELIMITER  NEWLINE\n"
"BADCHARS          \",\n"

"# Map Info Record (header):\n"
"PROLOGUE M, \"Geocaches\", \"GPSBabel\", Geocaches, __FILE__\n"
"#\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"# L Records:\n"
"IFIELD  CONSTANT, \"L\", \"%s\"		# [L]ANDMARK\n"
"IFIELD  CONSTANT, \"Geocaches\", \"%s\"     # Category for Landmark Searches\n"
"IFIELD  DESCRIPTION, \"\", \"%-.40s\"       # Name\n"
"IFIELD  CONSTANT, \"1\", \"%s\"		# View at Zoom Level 1 (1-4)\n"
"IFIELD  LON_DECIMAL, \"\", \"%08.5f\"       # Longitude\n"
"IFIELD  LAT_DECIMAL, \"\", \"%08.5f\"       # Latitude\n"
;
static char mxf[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Ozi Explorer\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"# As used in mxf.c\n"
"#\n"
"#\n"

"DESCRIPTION		MapTech Exchange Format\n"
"EXTENSION		mxf\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMASPACE\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		,\"\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"IFIELD	DESCRIPTION, \"\", \"\"%s\"\"\n"
"IFIELD	SHORTNAME, \"\", \"\"%s\"\"\n"
"IFIELD	IGNORE, \"\", \"%s\"\n"
"IFIELD	CONSTANT, \"ff0000\", \"%s\"	# COLOR\n"
"IFIELD	CONSTANT, \"47\", \"%s\"		# ICON\n"

"OFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	DESCRIPTION, \"\", \"\"%s\"\"\n"
"OFIELD	SHORTNAME, \"\", \"\"%s\"\"\n"
"OFIELD	DESCRIPTION, \"\", \"\"%s\"\"\n"
"OFIELD	CONSTANT, \"ff0000\", \"%s\"	# COLOR\n"
"OFIELD	CONSTANT, \"47\", \"%s\"		# ICON\n"
;
static char navigonwpt[] = 
"# gpsbabel XCSV style file\n"
"# Author: Tom Glaab\n"
"#\n"
"DESCRIPTION     Navigon Waypoints\n"
"SHORTLEN        8\n"
"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER         |\n"
"RECORD_DELIMITER        NEWLINE\n"
"BADCHARS                |\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"

"OFIELD  SHORTNAME, \"\",\"[%-.14s \"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"\",\"]\"\n"
"OFIELD  CONSTANT, \"%s\",\"[0][17]\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD  LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"\"\n"
"OFIELD  CONSTANT, \"%s\",\"49\"\n"
;
static char nima[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: NIMA/GNIS Geographic Names File\n"
"# Author: Alex Mottram\n"
"#   Date: 11/24/2002\n"
"#\n"

"DESCRIPTION	 NIMA/GNIS Geographic Names File\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		TAB\n"
"PROLOGUE	RC	UFI	UNI	DD_LAT	DD_LONG	DMS_LAT	DMS_LONG	UTM	JOG	FC	DSG	PC	CC1	ADM1	ADM2	DIM	CC2	NT	LC	SHORT_FORM	GENERIC	SORT_NAME	FULL_NAME	FULL_NAME_ND	MODIFY_DATE\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	IGNORE, \"\", \"%s\"		# RC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UFI\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UNI\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"		# DD_LAT\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"		# DD_LON\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DMS_LAT\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DMS_LON\n"
"IFIELD	IGNORE, \"\", \"%s\"		# UTM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# JOG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# FC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DSG\n"
"IFIELD	IGNORE, \"\", \"%s\"		# PC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# CC1\n"
"IFIELD	IGNORE, \"\", \"%s\"		# ADM1\n"
"IFIELD	IGNORE, \"\", \"%s\"		# ADM2\n"
"IFIELD	IGNORE, \"\", \"%s\"		# DIM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# CC2\n"
"IFIELD	IGNORE, \"\", \"%s\"		# NT\n"
"IFIELD	IGNORE, \"\", \"%s\"		# LC\n"
"IFIELD	IGNORE, \"\", \"%s\"		# SHORT_FORM\n"
"IFIELD	IGNORE, \"\", \"%s\"		# GENERIC\n"
"IFIELD	SHORTNAME, \"\", \"%s\"		# SORT_NAME \n"
"IFIELD	IGNORE, \"\", \"%s\"		# FULL_NAME (unicoded!)\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"		# FULL_NAME_ND\n"
"IFIELD	IGNORE, \"\", \"%s\"		# MODIFY_DATE\n"
;
static char openoffice[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Tab delimited useful for OpenOffice, Ploticus etc.\n"
"# Author: Tobias Minich\n"
"#   Date: 07/18/2005\n"
"#\n"
"#\n"

"DESCRIPTION		Tab delimited fields useful for OpenOffice, Ploticus etc.\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		TAB\n"

"#\n"
"# HEADER STUFF:\n"
"#\n"
"PROLOGUE	Index	Lat			Lon			Icon	Name	Description	Notes	URL	Link Text	Altitude (m)	Distance (km)	Speed (m/s)	Course (°)	Time	HDOP	VDOP	PDOP	Satellites	Fix\n"

"#\n"
"# INDIVIDUAL DATA FIELDS:\n"
"#\n"
"IFIELD	INDEX, \"\", \"%d\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LAT_DIR, \"\", \"%c\"\n"
"IFIELD	LAT_HUMAN_READABLE, \"\", \"%d° %f' %c\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LON_DIR, \"\", \"%c\"\n"
"IFIELD	LON_HUMAN_READABLE, \"\", \"%d° %f' %c\"\n"
"IFIELD	ICON_DESCR, \"\", \"%s\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	NOTES, \"\", \"%s\"\n"
"IFIELD	URL, \"\", \"%s\" 		\n"
"IFIELD	URL_LINK_TEXT, \"\", \"%s\"\n"
"IFIELD	ALT_METERS, \"\", \"%f\"\n"
"IFIELD	PATH_DISTANCE_KM, \"\", \"%f\"\n"
"IFIELD	PATH_SPEED, \"\", \"%f\"\n"
"IFIELD	PATH_COURSE, \"\", \"%f\"\n"
"IFIELD	EXCEL_TIME, \"\", \"%f\"\n"
"IFIELD	GPS_HDOP, \"\", \"%f\"\n"
"IFIELD	GPS_VDOP, \"\", \"%f\"\n"
"IFIELD	GPS_PDOP, \"\", \"%f\"\n"
"IFIELD	GPS_SAT, \"\", \"%d\"\n"
"IFIELD	GPS_FIX, \"\", \"%s\"\n"
;
static char ricoh[] = 
"DESCRIPTION Ricoh GPS Log File\n"
"EXTENSION log\n"
"DATATYPE TRACK\n"

"FIELD_DELIMITER COMMA\n"
"RECORD_DELIMITER NEWLINE\n"

"IFIELD LON_DECIMAL,\"\",\"%f\"\n"
"IFIELD LAT_DECIMAL,\"\",\"%f\"\n"
"IFIELD ALT_METERS,\"\",\"%f\"\n"
"IFIELD TRACK_NEW,\"\",\"%d\"\n"
"IFIELD GMT_TIME,\"\",\"%d-%m-%Y %H:%M:%S\"\n"

;
static char s_and_t[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: MS S&T 2002/2003\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"# As requested by Noel Shrum on the gpsbabel-code mailing list.\n"
"# Name,Latitude,Longitude,Name 2,URL,Type\n"
"# GCCBF,44.479133,-85.56515,High Rollaway by rjlint,http://www.geocaching.com/seek/cache_details.aspx?ID=3263,Traditional Cache\n"
"# GC110D,44.6522,-85.492483,Brown Bridge Pond Peek-a-Boo Cache by Big Bird,http://www.geocaching.com/seek/cache_details.aspx?ID=4365,Traditional Cache\n"
"# GC171C,44.70605,-85.62265,The Michigan Frog by RealDcoy & LRB,http://www.geocaching.com/seek/cache_details.aspx?ID=5916,Traditional Cache\n"
"#\n"

"DESCRIPTION 		Microsoft Streets and Trips 2002-2007\n"
"EXTENSION               txt\n"


"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		,\"\n"

"PROLOGUE	Name	Latitude	Longitude	Description	URL	Type	Container	Diff	Terr\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"# NOTE: MS S&T ONLY IMPORTS DATA, IT DOESN'T EXPORT THIS ANYWHERE SO WE CAN\n"
"#       HAVE OUR WAY WITH THE FORMATTING. \n"
"#\n"
"IFIELD	SHORTNAME, \"\", \"%s\"		# Name\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"		# Latitude\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"		# Longitude\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"		# Name 2 (Big Description)\n"
"IFIELD	URL, \"\", \"%s\"			# URL\n"
"IFIELD	GEOCACHE_TYPE, \"\", \"%s\"		# Geocache Type\n"
"IFIELD	GEOCACHE_CONTAINER, \"\", \"%s\"	# Geocache Type\n"
"IFIELD	GEOCACHE_DIFF, \"\", \"%3.1f\"	# Geocache Type\n"
"IFIELD	GEOCACHE_TERR, \"\", \"%3.1f\"	# Geocache Type\n"
;
static char saplus[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: \n"
"# Author: Jim Bensman\n"
"#   Date: 02/22/04\n"
"#\n"

"DESCRIPTION             DeLorme Street Atlas Plus\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER         COMMA\n"
"RECORD_DELIMITER        NEWLINE\n"
"BADCHARS                ,\"\n"

"PROLOGUE        Name 2,Name,Latitude,Longitude,URL,Type\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD  DESCRIPTION, \"\", \"%s\"           # Name 2 (Big Description)\n"
"IFIELD  SHORTNAME, \"\", \"%s\"             # Name\n"
"IFIELD  LAT_DECIMAL, \"\", \"%f\"           # Latitude\n"
"IFIELD  LON_DECIMAL, \"\", \"%f\"           # Longitude\n"
"IFIELD  URL, \"\", \"%s\"                   # URL\n"
"IFIELD  IGNORE, \"\", \"\"                  # Holder for Geocache Type\n"

;
static char sportsim[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Sportsim track files\n"
"# Author: Olaf Klein\n"
"#   Date: 07/05/2006\n"
"#\n"
"DESCRIPTION	Sportsim track files (part of zipped .ssz files) \n"
"EXTENSION	txt\n"
"DATATYPE	TRACK\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		SEMICOLON\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		TAB\n"

"#\n"
"# FILE HEADER\n"
"#\n"
"PROLOGUE	ï»¿SportsimVersion:01\n"
"PROLOGUE	\\#Sportsim TrackFile\n"

"#\n"
"# INDIVIDUAL DATA FIELDS:\n"
"#\n"
"IFIELD	INDEX, \"\", \"%05d\"\n"
"IFIELD	CONSTANT, \"0\", \"%s\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"\n"
"IFIELD	ALT_FEET, \"\", \"%.f\"\n"
"IFIELD	TIMET_TIME, \"\", \"%ld\"\n"
"IFIELD	CONSTANT, \";\", \"%s\"\n"
;
static char tabsep[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: Dumps all fields in a traditional Unix tab separated style\n"
"#\n"
"# The order of the fields (with the exception of LAT_DIR/LON_DIR) was\n"
"# the same as documented in README.style when this format was created.\n"
"# LAT_DIR/LON_DIR were undocumented, so I stuck them at the end of the\n"
"# other lat/lon fields.\n"
"#\n"
"# However, please add any new gpsbabel fields to the end (to avoid\n"
"# upsetting existing applications) regardless of where they land in\n"
"# the README.style documentation.\n"
"#\n"

"DESCRIPTION		All database fields on one tab-separated line\n"

"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		TAB\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		TAB\n"
"FORMAT_TYPE		INTERNAL\n"

"#\n"
"# INDIVIDUAL DATA FIELDS:\n"
"#\n"
"IFIELD	INDEX, \"\", \"%d\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"
"IFIELD	NOTES, \"\", \"%s\"\n"
"IFIELD	URL, \"\", \"%s\" 		\n"
"IFIELD	URL_LINK_TEXT, \"\", \"%s\"\n"
"IFIELD	ICON_DESCR, \"\", \"%s\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LON_DECIMAL, \"\", \"%f\"\n"
"IFIELD	LAT_INT32DEG, \"\", \"%ld\"\n"
"IFIELD	LON_INT32DEG, \"\", \"%ld\"\n"
"IFIELD	LAT_DECIMALDIR, \"\", \"%f%c\"\n"
"IFIELD	LON_DECIMALDIR, \"\", \"%f%c\"\n"
"IFIELD	LAT_DIRDECIMAL, \"\", \"%c%f\"\n"
"IFIELD	LON_DIRDECIMAL, \"\", \"%c%f\"\n"
"IFIELD	LAT_DIR, \"\", \"%c\"\n"
"IFIELD	LON_DIR, \"\", \"%c\"\n"
"IFIELD	ALT_FEET, \"\", \"%fF\"\n"
"IFIELD	ALT_METERS, \"\", \"%fM\"\n"
"IFIELD	EXCEL_TIME, \"\", \"%f\"\n"
"IFIELD	TIMET_TIME, \"\", \"%ld\"\n"
"IFIELD  GEOCACHE_DIFF,\"\",\"%3.1f\"\n"
"IFIELD  GEOCACHE_TERR,\"\",\"%3.1f\"\n"
"IFIELD  GEOCACHE_CONTAINER,\"\",\"%s\"\n"
"IFIELD  GEOCACHE_TYPE,\"\",\"%s\"\n"
"IFIELD  PATH_DISTANCE_MILES,\"\",\"%f\"\n"
"IFIELD  PATH_DISTANCE_KM, \"\", \"%f\"\n"
"IFIELD  GEOCACHE_PLACER,\"\",\"%s\"\n"
"IFIELD  YYYYMMDD_TIME,\"\",\"%ld\"\n"
"IFIELD	GEOCACHE_HINT, \"\", \"%s\"\n"
"IFIELD	GEOCACHE_LAST_FOUND, \"\", \"%d\"\n"
;
static char tomtom_asc[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: TomTom Navigator Places of Interest\n"
"# Author: Olaf Klein\n"
"#   Date: 04/17/2007\n"
"#\n"
"DESCRIPTION		TomTom POI file (.asc)\n"
"EXTENSION		asc\n"
"DATATYPE		WAYPOINT\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		,\"\n"
"ENCODING		MS-ANSI\n"
"#\n"
"PROLOGUE	 TomTom Navigator Places of Interest\n"
"PROLOGUE	 GPSBabel-__VERSION__ ASCII Export\n"
"PROLOGUE	  Points\n"
"PROLOGUE	 Created at: __DATE_AND_TIME__\n"
"# #\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LON_DECIMAL, \"\", \"%.6f\"\n"
"IFIELD	LAT_DECIMAL, \"\", \"%.6f\"\n"
"IFIELD	SHORTNAME, \"\", \"\"%s\"\"\n"
;
static char tomtom_itn[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: TomTom Navigator Itineraries (Routes)\n"
"# Author: Olaf Klein\n"
"#   Date: 04/17/2007\n"
"#\n"
"DESCRIPTION		TomTom Itineraries (.itn)\n"
"EXTENSION		itn\n"
"DATATYPE		ROUTE\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		PIPE\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		,|\n"
"ENCODING		MS-ANSI\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LON_10E5, \"\", \"%.f\"\n"
"IFIELD	LAT_10E5, \"\", \"%.f\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	CONSTANT, \"0\", \"%s\"\n"
;
static char tomtom_itn_places[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: TomTom Navigator Itineraries (Routes)\n"
"# Author: Olaf Klein\n"
"#   Date: 04/17/2007\n"
"#\n"
"DESCRIPTION		TomTom Places Itineraries (.itn)\n"
"EXTENSION		itn\n"
"DATATYPE		ROUTE\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		PIPE\n"
"RECORD_DELIMITER	CRNEWLINE\n"
"BADCHARS		,|\n"
"ENCODING		MS-ANSI\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LON_10E5, \"\", \"%.f\"\n"
"IFIELD	LAT_10E5, \"\", \"%.f\"\n"
"IFIELD	SHORTNAME, \"\", \"%s\"\n"
"IFIELD	CONSTANT, \"2\", \"%s\"\n"
;
static char xmap[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: DeLorme Xmap Conduit\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"# As defined in csv.c/xmap\n"
"#\n"

"DESCRIPTION		DeLorme XMap HH Native .WPT\n"
"EXTENSION		wpt\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMASPACE\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COMMA\n"

"PROLOGUE	BEGIN SYMBOL\n"
"EPILOGUE	END\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	LAT_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD	LON_HUMAN_READABLE, \"\", \"%08.5f\"\n"
"IFIELD	DESCRIPTION, \"\", \"%s\"\n"

"OFIELD	LAT_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	LON_DECIMAL, \"\", \"%08.5f\"\n"
"OFIELD	DESCRIPTION, \"\", \"%s\"\n"
;
static char xmap2006[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: DeLorme Xmap/Street Atlas Handheld 2006 Conduit\n"
"# Author: Pasha Phares\n"
"#   Date: 5/5/2006\n"
"#\n"
"# Amazingly, 2006 won't read the \"COMMASPACE\" that we used in \n"
"# in Xmap prior to this and versions before 2006 won't read files\n"
"# separated by only a comma.\n"
"# \n"

"DESCRIPTION			DeLorme XMap/SAHH 2006 Native .TXT\n"
"EXTENSION			txt\n"

"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COMMA\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS			COMMA\n"

"PROLOGUE	BEGIN SYMBOL\n"
"EPILOGUE	END\n"
"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD				LAT_HUMAN_READABLE, \"\", \"%.12g\"\n"
"IFIELD				LON_HUMAN_READABLE, \"\", \"%.12g\"\n"
"IFIELD				SHORTNAME, \"\", \"%s\"\n"

"OFIELD				LAT_DECIMAL, \"\", \"%.12g\"\n"
"OFIELD				LON_DECIMAL, \"\", \"%.12g\"\n"
"OFIELD				SHORTNAME, \"\", \"%s\"\n"




;
static char xmapwpt[] = 
"# gpsbabel XCSV style file\n"
"#\n"
"# Format: DeLorme Xmap HH Street Atlas USA .WPT (PocketPC)\n"
"# Author: Alex Mottram\n"
"#   Date: 12/09/2002\n"
"#\n"
"# \n"
"DESCRIPTION 		DeLorme XMat HH Street Atlas USA .WPT (PPC)\n"
"SHORTLEN		32\n"
"SHORTWHITE		0\n"

"#\n"
"#\n"
"# FILE LAYOUT DEFINITIIONS:\n"
"#\n"
"FIELD_DELIMITER		COLON\n"
"RECORD_DELIMITER	NEWLINE\n"
"BADCHARS		COLON\n"

"#\n"
"# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:\n"
"#\n"
"IFIELD	CONSTANT, \"1296126539\", \"%s\"\n"
"IFIELD	CONSTANT, \"1481466224\", \"%s\"\n"
"IFIELD	LAT_INT32DEG, \"\", \"%d\"\n"
"IFIELD	LON_INT32DEG, \"\", \"%d\"\n"
"IFIELD	CONSTANT, \"3137157\", \"%s\"\n"
"IFIELD	SHORTNAME, \"\", \"%-.31s\"\n"
"IFIELD	IGNORE, \"\", \"%-.31s\"\n"
"IFIELD	DESCRIPTION, \"\", \"%-.78s\"\n"
;
style_vecs_t style_list[] = {{ "xmapwpt", xmapwpt } , { "xmap2006", xmap2006 } , { "xmap", xmap } , { "tomtom_itn_places", tomtom_itn_places } , { "tomtom_itn", tomtom_itn } , { "tomtom_asc", tomtom_asc } , { "tabsep", tabsep } , { "sportsim", sportsim } , { "saplus", saplus } , { "s_and_t", s_and_t } , { "ricoh", ricoh } , { "openoffice", openoffice } , { "nima", nima } , { "navigonwpt", navigonwpt } , { "mxf", mxf } , { "mapconverter", mapconverter } , { "kwf2", kwf2 } , { "ktf2", ktf2 } , { "kompass_wp", kompass_wp } , { "kompass_tk", kompass_tk } , { "igo2008_poi", igo2008_poi } , { "iblue747", iblue747 } , { "gpsman", gpsman } , { "gpsdrivetrack", gpsdrivetrack } , { "gpsdrive", gpsdrive } , { "geonet", geonet } , { "garmin_poi", garmin_poi } , { "garmin301", garmin301 } , { "fugawi", fugawi } , { "flysight", flysight } , { "dna", dna } , { "custom", custom } , { "cup", cup } , { "csv", csv } , { "cambridge", cambridge } , { "arc", arc } ,  {0,0}};
size_t nstyles = 36;
#else /* CSVFMTS_ENABLED */
style_vecs_t style_list[] = {{0,0}};
size_t nstyles = 0;
#endif /* CSVFMTS_ENABLED */
