#!/bin/sh

#
# Run our testsuite under valgrind.  Mostly it complains about core GNU libc
# functions, but it does actually help find interesting stuff in our own code
# from time to time.
#

QUIET="-q"
BASEPATH=`dirname $0`

while getopts "l" opt; do
  case $opt in
    l) OPTS="--leak-check=full --show-reachable=yes --suppressions=gpsbabel.supp" ; QUIET="";;
  esac
done
shift $(($OPTIND -1))

PNAME="valgrind $OPTS --error-exitcode=1 $QUIET ./gpsbabel" ${BASEPATH}/testo $*
