#!/bin/sh

#
# Run our testsuite under valgrind.  Mostly it complains about core GNU libc
# functions, but it does actually help find interesting stuff in our own code
# from time to time.
#

BASEPATH=`dirname $0`
PNAME="valgrind --error-exitcode=1 -q ./gpsbabel" ${BASEPATH}/testo $*
