QT_TRANSLATE_NOOP("core","Alan Map500 tracklogs (.trl)")
QT_TRANSLATE_NOOP("core","Alan Map500 waypoints and routes (.wpr)")
QT_TRANSLATE_NOOP("core","Brauniger IQ Series Barograph Download")
QT_TRANSLATE_NOOP("core","Bushnell GPS Trail file")
QT_TRANSLATE_NOOP("core","Bushnell GPS Waypoint file")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Cambridge/Winpilot glider software")
QT_TRANSLATE_NOOP("core","CarteSurTable data file")
QT_TRANSLATE_NOOP("core","Columbus/Visiontac V900 files (.csv)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Comma separated values")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Index of route/track to write (if more than one in source)")
QT_TRANSLATE_NOOP("core","Give points (waypoints/route points) a default radius (proximity)")
QT_TRANSLATE_NOOP("core","Length of generated shortnames (default 16)")
QT_TRANSLATE_NOOP("core","CompeGPS data files (.wpt/.trk/.rte)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Data Logger iBlue747 csv")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Data Logger iBlue757 csv")
QT_TRANSLATE_NOOP("core","Type of .an1 file")
QT_TRANSLATE_NOOP("core","Road type changes")
QT_TRANSLATE_NOOP("core","Do not add geocache data to description")
QT_TRANSLATE_NOOP("core","Do not add URLs to description")
QT_TRANSLATE_NOOP("core","Symbol to use for point data")
QT_TRANSLATE_NOOP("core","Color for lines or mapnotes")
QT_TRANSLATE_NOOP("core","Zoom level to reduce points")
QT_TRANSLATE_NOOP("core","Waypoint type")
QT_TRANSLATE_NOOP("core","Radius for circles")
QT_TRANSLATE_NOOP("core","DeLorme .an1 (drawing) file")
QT_TRANSLATE_NOOP("core","DeLorme GPL")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","DeLorme Street Atlas Plus")
QT_TRANSLATE_NOOP("core","Keep turns if simplify filter is used")
QT_TRANSLATE_NOOP("core","Only read turns; skip all other points")
QT_TRANSLATE_NOOP("core","Split into multiple routes at turns")
QT_TRANSLATE_NOOP("core","Read control points as waypoint/route/none")
QT_TRANSLATE_NOOP("core","Synthesize track times")
QT_TRANSLATE_NOOP("core","DeLorme Street Atlas Route")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","DeLorme XMap HH Native .WPT")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","DeLorme XMap/SAHH 2006 Native .TXT")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","DeLorme XMat HH Street Atlas USA .WPT (PPC)")
QT_TRANSLATE_NOOP("core","Destinator Itineraries (.dat)")
QT_TRANSLATE_NOOP("core","Destinator Points of Interest (.dat)")
QT_TRANSLATE_NOOP("core","Destinator TrackLogs (.dat)")
QT_TRANSLATE_NOOP("core","EasyGPS binary format")
QT_TRANSLATE_NOOP("core","Set waypoint name to source filename")
QT_TRANSLATE_NOOP("core","Time-frame (in seconds)")
QT_TRANSLATE_NOOP("core","Locate waypoint for tagging by this name")
QT_TRANSLATE_NOOP("core","!OVERWRITE! the original file. Default=N")
QT_TRANSLATE_NOOP("core","Embedded Exif-GPS data (.jpg)")
QT_TRANSLATE_NOOP("core","Energympro GPS training watch")
QT_TRANSLATE_NOOP("core","Enigma binary waypoint file (.ert)")
QT_TRANSLATE_NOOP("core","Source for name field in .dbf")
QT_TRANSLATE_NOOP("core","Source for URL field in .dbf")
QT_TRANSLATE_NOOP("core","ESRI shapefile")
QT_TRANSLATE_NOOP("core","F90G Automobile DVR GPS log file")
QT_TRANSLATE_NOOP("core","(integer sec or 'auto') Barograph to GPS time diff")
QT_TRANSLATE_NOOP("core","FAI/IGC Flight Recorder Data Format")
QT_TRANSLATE_NOOP("core","Read all points even if latitude or longitude is missing")
QT_TRANSLATE_NOOP("core","Flexible and Interoperable Data Transfer (FIT) Activity file")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","FlySight GPS File")
QT_TRANSLATE_NOOP("core","Default speed for waypoints (knots/hr)")
QT_TRANSLATE_NOOP("core","Split input into separate files")
QT_TRANSLATE_NOOP("core","Franson GPSGate Simulation")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Fugawi")
QT_TRANSLATE_NOOP("core","G7ToWin data files (.g7t)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Garmin 301 Custom position and heartrate")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Garmin G1000 datalog input filter file")
QT_TRANSLATE_NOOP("core","Garmin Logbook XML")
QT_TRANSLATE_NOOP("core","Default category on output (1..16)")
QT_TRANSLATE_NOOP("core","Bitmap of categories")
QT_TRANSLATE_NOOP("core","Version of gdb file to generate (1..3)")
QT_TRANSLATE_NOOP("core","Drop route points that do not have an equivalent waypoint (hidden points)")
QT_TRANSLATE_NOOP("core","Include major turn points (with description) from calculated route")
QT_TRANSLATE_NOOP("core","Garmin MapSource - gdb")
QT_TRANSLATE_NOOP("core","Length of generated shortnames")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","Version of mapsource file to generate (3,4,5)")
QT_TRANSLATE_NOOP("core","Merge output with existing file")
QT_TRANSLATE_NOOP("core","Use depth values on output (default is ignore)")
QT_TRANSLATE_NOOP("core","Use proximity values on output (default is ignore)")
QT_TRANSLATE_NOOP("core","Garmin MapSource - mps")
QT_TRANSLATE_NOOP("core","Read/Write date format (i.e. yyyy/mm/dd)")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Distance unit [m=metric, s=statute]")
QT_TRANSLATE_NOOP("core","Write position using this grid.")
QT_TRANSLATE_NOOP("core","Precision of coordinates")
QT_TRANSLATE_NOOP("core","Temperature unit [c=Celsius, f=Fahrenheit]")
QT_TRANSLATE_NOOP("core","Read/Write time format (i.e. HH:mm:ss xx)")
QT_TRANSLATE_NOOP("core","Write timestamps with offset x to UTC time")
QT_TRANSLATE_NOOP("core","Garmin MapSource - txt (tab delimited)")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Write tracks compatible with Carto Exploreur")
QT_TRANSLATE_NOOP("core","Garmin PCX5")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Garmin POI database")
QT_TRANSLATE_NOOP("core","Enable alerts on speed or proximity distance")
QT_TRANSLATE_NOOP("core","Use specified bitmap on output")
QT_TRANSLATE_NOOP("core","Default category on output")
QT_TRANSLATE_NOOP("core","Don't show gpi bitmap on device")
QT_TRANSLATE_NOOP("core","Write description to address field")
QT_TRANSLATE_NOOP("core","Write notes to address field")
QT_TRANSLATE_NOOP("core","Write position to address field")
QT_TRANSLATE_NOOP("core","Default proximity")
QT_TRANSLATE_NOOP("core","After output job done sleep n second(s)")
QT_TRANSLATE_NOOP("core","Default speed")
QT_TRANSLATE_NOOP("core","Create unique waypoint names (default = yes)")
QT_TRANSLATE_NOOP("core","Units used for names with @speed ('s'tatute or 'm'etric)")
QT_TRANSLATE_NOOP("core","codec to use for writing strings")
QT_TRANSLATE_NOOP("core","language code to use for reading dual language files")
QT_TRANSLATE_NOOP("core","Garmin Points of Interest (.gpi)")
QT_TRANSLATE_NOOP("core","Length of generated shortnames")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Return current position as a waypoint")
QT_TRANSLATE_NOOP("core","Command unit to power itself down")
QT_TRANSLATE_NOOP("core","Erase existing courses when writing new ones")
QT_TRANSLATE_NOOP("core","Sync GPS time to computer time")
QT_TRANSLATE_NOOP("core","Category number to use for written waypoints")
QT_TRANSLATE_NOOP("core","Bitmap of categories")
QT_TRANSLATE_NOOP("core","Speed in bits per second of serial port (baud=9600)")
QT_TRANSLATE_NOOP("core","Garmin serial/USB protocol")
QT_TRANSLATE_NOOP("core","Write course rather than history, default yes")
QT_TRANSLATE_NOOP("core","Sport: Biking (deflt), Running, MultiSport, Other")
QT_TRANSLATE_NOOP("core","Garmin Training Center (.tcx/.crs/.hst/.xml)")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Omit Placer name")
QT_TRANSLATE_NOOP("core","Geocaching.com .loc")
QT_TRANSLATE_NOOP("core","Geogrid-Viewer ascii overlay file (.ovl)")
QT_TRANSLATE_NOOP("core","Geogrid-Viewer binary overlay file (.ovl)")
QT_TRANSLATE_NOOP("core","Geogrid-Viewer tracklogs (.log)")
QT_TRANSLATE_NOOP("core","Compact Output. Default is off.")
QT_TRANSLATE_NOOP("core","GeoJson")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GEOnet Names Server (GNS)")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Only erase device data, do not download anything")
QT_TRANSLATE_NOOP("core","GlobalSat DG-100/BT-335 Download")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Only erase device data, do not download anything")
QT_TRANSLATE_NOOP("core","GlobalSat DG-200 Download")
QT_TRANSLATE_NOOP("core","list tracks")
QT_TRANSLATE_NOOP("core","get track")
QT_TRANSLATE_NOOP("core","Dump raw data to this file")
QT_TRANSLATE_NOOP("core","Dump raw data to this file")
QT_TRANSLATE_NOOP("core","GlobalSat GH625XT GPS training watch")
QT_TRANSLATE_NOOP("core","Google Directions XML")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Export linestrings for tracks and routes")
QT_TRANSLATE_NOOP("core","Export placemarks for tracks and routes")
QT_TRANSLATE_NOOP("core","Width of lines, in pixels")
QT_TRANSLATE_NOOP("core","Line color, specified in hex AABBGGRR")
QT_TRANSLATE_NOOP("core","Altitudes are absolute and not clamped to ground")
QT_TRANSLATE_NOOP("core","Draw extrusion line from trackpoint to ground")
QT_TRANSLATE_NOOP("core","Write KML track (default = 0)")
QT_TRANSLATE_NOOP("core","Include extended data for trackpoints (default = 1)")
QT_TRANSLATE_NOOP("core","Indicate direction of travel in track icons (default = 0)")
QT_TRANSLATE_NOOP("core","Units used when writing comments ('s'tatute, 'm'etric,' 'n'autical, 'a'viation)")
QT_TRANSLATE_NOOP("core","Display labels on track and routepoints  (default = 1)")
QT_TRANSLATE_NOOP("core","Retain at most this number of position points  (0 = unlimited)")
QT_TRANSLATE_NOOP("core","Rotate colors for tracks and routes (default automatic)")
QT_TRANSLATE_NOOP("core","Precision of coordinates, number of decimals")
QT_TRANSLATE_NOOP("core","Google Earth (Keyhole) Markup Language")
QT_TRANSLATE_NOOP("core","Google Navigator Tracklines (.trl)")
QT_TRANSLATE_NOOP("core","Complete date-free tracks with given date (YYYYMMDD).")
QT_TRANSLATE_NOOP("core","The maximum speed (km/h) traveling from waypoint to waypoint.")
QT_TRANSLATE_NOOP("core","The minimum speed (km/h) traveling from waypoint to waypoint. Set >0 to remove duplicate waypoints")
QT_TRANSLATE_NOOP("core","Cleanup common errors in trackdata")
QT_TRANSLATE_NOOP("core","GoPal GPS track log (.trk)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GPS Tracking Key Pro text")
QT_TRANSLATE_NOOP("core","GPS TrackMaker")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GPSBabel arc filter file")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GpsDrive Format")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GpsDrive Format for Tracks")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","GPSman")
QT_TRANSLATE_NOOP("core","gpsutil")
QT_TRANSLATE_NOOP("core","Length of generated shortnames")
QT_TRANSLATE_NOOP("core","No whitespace in generated shortnames")
QT_TRANSLATE_NOOP("core","Create waypoints from geocache log entries")
QT_TRANSLATE_NOOP("core","Base URL for link tag in output")
QT_TRANSLATE_NOOP("core","Target GPX version for output")
QT_TRANSLATE_NOOP("core","Add info (depth) as Humminbird extension")
QT_TRANSLATE_NOOP("core","Add info (depth) as Garmin extension")
QT_TRANSLATE_NOOP("core","Precision of elevations, number of decimals")
QT_TRANSLATE_NOOP("core","GPX XML")
QT_TRANSLATE_NOOP("core","HikeTech")
QT_TRANSLATE_NOOP("core","Holux (gm-100) .wpo Format")
QT_TRANSLATE_NOOP("core","MTK compatible CSV output file")
QT_TRANSLATE_NOOP("core","Holux M-241 (MTK based) Binary File Format")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Only erase device data, do not download anything")
QT_TRANSLATE_NOOP("core","Enable logging after download")
QT_TRANSLATE_NOOP("core","MTK compatible CSV output file")
QT_TRANSLATE_NOOP("core","Size of blocks in KB to request from device")
QT_TRANSLATE_NOOP("core","Holux M-241 (MTK based) download")
QT_TRANSLATE_NOOP("core","Honda/Acura Navigation System VP Log File Format")
QT_TRANSLATE_NOOP("core","Path to HTML style sheet")
QT_TRANSLATE_NOOP("core","Encrypt hints using ROT13")
QT_TRANSLATE_NOOP("core","Include groundspeak logs if present")
QT_TRANSLATE_NOOP("core","Degrees output as 'ddd', 'dmm'(default) or 'dms'")
QT_TRANSLATE_NOOP("core","Units for altitude (f)eet or (m)etres")
QT_TRANSLATE_NOOP("core","HTML Output")
QT_TRANSLATE_NOOP("core","Humminbird tracks (.ht)")
QT_TRANSLATE_NOOP("core","Humminbird waypoints and routes (.hwr)")
QT_TRANSLATE_NOOP("core","Index of track to write (if more than one in source)")
QT_TRANSLATE_NOOP("core","IGN Rando track files")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","iGo Primo points of interest (.upoi)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","iGO2008 points of interest (.upoi)")
QT_TRANSLATE_NOOP("core","Track identification number")
QT_TRANSLATE_NOOP("core","Track title")
QT_TRANSLATE_NOOP("core","Track description")
QT_TRANSLATE_NOOP("core","IGO8 .trk")
QT_TRANSLATE_NOOP("core","Jelbert GeoTagger data file")
QT_TRANSLATE_NOOP("core","Jogmap.de XML format")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Kompass (DAV) Track (.tk)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Kompass (DAV) Waypoints (.wp)")
QT_TRANSLATE_NOOP("core","KuDaTa PsiTrex text")
QT_TRANSLATE_NOOP("core","(USR input) Ignore event marker icons on read")
QT_TRANSLATE_NOOP("core","(USR output) Treat waypoints as icons on write")
QT_TRANSLATE_NOOP("core","(USR output) Merge into one segmented trail")
QT_TRANSLATE_NOOP("core","(USR input) Break segments into separate trails")
QT_TRANSLATE_NOOP("core","(USR input) Read version")
QT_TRANSLATE_NOOP("core","(USR output) Write version")
QT_TRANSLATE_NOOP("core","(USR output) Output file title string")
QT_TRANSLATE_NOOP("core","(USR output) Device serial number")
QT_TRANSLATE_NOOP("core","(USR output) Output file content description")
QT_TRANSLATE_NOOP("core","Lowrance USR")
QT_TRANSLATE_NOOP("core","Magellan Explorist Geocaching")
QT_TRANSLATE_NOOP("core","MapSend version TRK file to generate (3,4)")
QT_TRANSLATE_NOOP("core","Magellan Mapsend")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Max number of comments to write (maxcmts=200)")
QT_TRANSLATE_NOOP("core","Magellan SD files (as for eXplorist)")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Max number of comments to write (maxcmts=200)")
QT_TRANSLATE_NOOP("core","Magellan SD files (as for Meridian)")
QT_TRANSLATE_NOOP("core","Default icon name")
QT_TRANSLATE_NOOP("core","Max number of comments to write (maxcmts=200)")
QT_TRANSLATE_NOOP("core","Numeric value of bitrate (baud=4800)")
QT_TRANSLATE_NOOP("core","Suppress use of handshaking in name of speed")
QT_TRANSLATE_NOOP("core","Delete all waypoints")
QT_TRANSLATE_NOOP("core","Magellan serial protocol")
QT_TRANSLATE_NOOP("core","MagicMaps IK3D project file (.ikt)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Mainnav")
QT_TRANSLATE_NOOP("core","Include only via stations in route")
QT_TRANSLATE_NOOP("core","Map&Guide 'TourExchangeFormat' XML")
QT_TRANSLATE_NOOP("core","MapAsia track file (.tr7)")
QT_TRANSLATE_NOOP("core","Mapbar (China) navigation track for Sonim Xp3300")
QT_TRANSLATE_NOOP("core","Mapfactor Navigator")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Mapopolis.com Mapconverter CSV")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","MapTech Exchange Format")
QT_TRANSLATE_NOOP("core","Speed in bits per second of serial port (autodetect=0)")
QT_TRANSLATE_NOOP("core","Download logged fixes")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Show device status")
QT_TRANSLATE_NOOP("core","Enable logging after download")
QT_TRANSLATE_NOOP("core","MediaTek Locus")
QT_TRANSLATE_NOOP("core","Write items 'locked' [default no]")
QT_TRANSLATE_NOOP("core","Write items 'visible' [default yes]")
QT_TRANSLATE_NOOP("core","Write files with internal version [n]")
QT_TRANSLATE_NOOP("core","Memory-Map Navigator overlay files (.mmo)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Microsoft Streets and Trips 2002-2007")
QT_TRANSLATE_NOOP("core","Baud rate used for download")
QT_TRANSLATE_NOOP("core","Dump raw data to this file")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","First sector to be read from the device")
QT_TRANSLATE_NOOP("core","Baud rate used to init device (0=autodetect)")
QT_TRANSLATE_NOOP("core","Last sector to be read from the device (-1: smart read everything)")
QT_TRANSLATE_NOOP("core","Disable output (useful with erase)")
QT_TRANSLATE_NOOP("core","Number of sectors to read at once (0=use single sector mode)")
QT_TRANSLATE_NOOP("core","POI for Home Symbol as lat:lng[:alt]")
QT_TRANSLATE_NOOP("core","POI for Car Symbol as lat:lng[:alt]")
QT_TRANSLATE_NOOP("core","POI for Boat Symbol as lat:lng[:alt]")
QT_TRANSLATE_NOOP("core","POI for Heart Symbol as lat:lng[:alt]")
QT_TRANSLATE_NOOP("core","POI for Bar Symbol as lat:lng[:alt]")
QT_TRANSLATE_NOOP("core","MiniHomer, a skyTraq Venus 6 based logger (download tracks, waypoints and get/set POI)")
QT_TRANSLATE_NOOP("core","Garmin Mobile XT ([ATRK]/STRK)")
QT_TRANSLATE_NOOP("core","Track name processing option ([0]-nrm/1-ign)")
QT_TRANSLATE_NOOP("core","Mobile Garmin XT Track files")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Motoactiv CSV")
QT_TRANSLATE_NOOP("core","Index of route to write (if more than one in source)")
QT_TRANSLATE_NOOP("core","New name for the route")
QT_TRANSLATE_NOOP("core","Radius of our big earth (default 6371000 meters)")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","Motorrad Routenplaner (Map&Guide) .bcr files")
QT_TRANSLATE_NOOP("core","MTK compatible CSV output file")
QT_TRANSLATE_NOOP("core","MTK Logger (iBlue 747,...) Binary File Format")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Only erase device data, do not download anything")
QT_TRANSLATE_NOOP("core","Enable logging after download")
QT_TRANSLATE_NOOP("core","MTK compatible CSV output file")
QT_TRANSLATE_NOOP("core","Size of blocks in KB to request from device")
QT_TRANSLATE_NOOP("core","MTK Logger (iBlue 747,Qstarz BT-1000,...) download")
QT_TRANSLATE_NOOP("core","MyNav TRC format")
QT_TRANSLATE_NOOP("core","Datum (default=NAD27)")
QT_TRANSLATE_NOOP("core","National Geographic Topo .tpg (waypoints)")
QT_TRANSLATE_NOOP("core","National Geographic Topo 2.x .tpo")
QT_TRANSLATE_NOOP("core","National Geographic Topo 3.x/4.x .tpo")
QT_TRANSLATE_NOOP("core","Suppress retired geocaches")
QT_TRANSLATE_NOOP("core","Navicache.com XML")
QT_TRANSLATE_NOOP("core","Index of route to write (if more than one in source)")
QT_TRANSLATE_NOOP("core","Navigon Mobile Navigator .rte files")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Navigon Waypoints")
QT_TRANSLATE_NOOP("core","Delete all track points")
QT_TRANSLATE_NOOP("core","Delete all routes")
QT_TRANSLATE_NOOP("core","Delete all waypoints")
QT_TRANSLATE_NOOP("core","Clear the datalog")
QT_TRANSLATE_NOOP("core","Read from datalogger buffer")
QT_TRANSLATE_NOOP("core","Command unit to power itself down")
QT_TRANSLATE_NOOP("core","NaviGPS GT-11/BGT-11 Download")
QT_TRANSLATE_NOOP("core","NaviGPS GT-31/BGT-31 datalogger (.sbp)")
QT_TRANSLATE_NOOP("core","NaviGPS GT-31/BGT-31 SiRF binary logfile (.sbn)")
QT_TRANSLATE_NOOP("core","'wp' - Create waypoint file , 'rte' - Create route file")
QT_TRANSLATE_NOOP("core","'n' - Keep the existing wp name, 'y' - rename waypoints")
QT_TRANSLATE_NOOP("core","Naviguide binary route file (.twl)")
QT_TRANSLATE_NOOP("core","Navitel binary track (.bin)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Navitrak DNA marker format")
QT_TRANSLATE_NOOP("core","Non-stealth encrypted icon name")
QT_TRANSLATE_NOOP("core","Non-stealth non-encrypted icon name")
QT_TRANSLATE_NOOP("core","Stealth encrypted icon name")
QT_TRANSLATE_NOOP("core","Stealth non-encrypted icon name")
QT_TRANSLATE_NOOP("core","Shortname is MAC address")
QT_TRANSLATE_NOOP("core","NetStumbler Summary File (text)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","NIMA/GNIS Geographic Names File")
QT_TRANSLATE_NOOP("core","Max length of waypoint name to write")
QT_TRANSLATE_NOOP("core","Read/write GPRMC sentences")
QT_TRANSLATE_NOOP("core","Read/write GPGGA sentences")
QT_TRANSLATE_NOOP("core","Read/write GPVTG sentences")
QT_TRANSLATE_NOOP("core","Read/write GPGSA sentences")
QT_TRANSLATE_NOOP("core","Complete date-free tracks with given date (YYYYMMDD).")
QT_TRANSLATE_NOOP("core","Return current position as a waypoint")
QT_TRANSLATE_NOOP("core","Decimal seconds to pause between groups of strings")
QT_TRANSLATE_NOOP("core","Append realtime positioning data to the output file instead of truncating")
QT_TRANSLATE_NOOP("core","Speed in bits per second of serial port (baud=4800)")
QT_TRANSLATE_NOOP("core","Write tracks for Gisteq Phototracker")
QT_TRANSLATE_NOOP("core","Accept position fixes in gpgga marked invalid")
QT_TRANSLATE_NOOP("core","NMEA 0183 sentences")
QT_TRANSLATE_NOOP("core","Compact binary representation")
QT_TRANSLATE_NOOP("core","Nokia Landmark Exchange")
QT_TRANSLATE_NOOP("core","Write additional way tag key/value pairs")
QT_TRANSLATE_NOOP("core","Write additional node tag key/value pairs")
QT_TRANSLATE_NOOP("core","Use this value as custom created_by value")
QT_TRANSLATE_NOOP("core","OpenStreetMap data files")
QT_TRANSLATE_NOOP("core","Write all tracks into one file")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Waypoint foreground color")
QT_TRANSLATE_NOOP("core","Waypoint background color")
QT_TRANSLATE_NOOP("core","Proximity distance")
QT_TRANSLATE_NOOP("core","Unit used in altitude values")
QT_TRANSLATE_NOOP("core","Unit used in proximity values")
QT_TRANSLATE_NOOP("core","OziExplorer")
QT_TRANSLATE_NOOP("core","PocketFMS breadcrumbs")
QT_TRANSLATE_NOOP("core","PocketFMS flightplan (.xml)")
QT_TRANSLATE_NOOP("core","PocketFMS waypoints (.txt)")
QT_TRANSLATE_NOOP("core","Default location")
QT_TRANSLATE_NOOP("core","Raymarine Waypoint File (.rwf)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Ricoh GPS Log File")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","See You flight analysis data")
QT_TRANSLATE_NOOP("core","Skymap / KMD150 ascii files")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Set location finder target location as lat,lng")
QT_TRANSLATE_NOOP("core","Configure logging parameter as tmin:tmax:dmin:dmax")
QT_TRANSLATE_NOOP("core","Baud rate used for download")
QT_TRANSLATE_NOOP("core","Baud rate used to init device (0=autodetect)")
QT_TRANSLATE_NOOP("core","Number of sectors to read at once (0=use single sector mode)")
QT_TRANSLATE_NOOP("core","First sector to be read from the device")
QT_TRANSLATE_NOOP("core","Last sector to be read from the device (-1: smart read everything)")
QT_TRANSLATE_NOOP("core","Dump raw data to this file")
QT_TRANSLATE_NOOP("core","Disable output (useful with erase)")
QT_TRANSLATE_NOOP("core","Seconds that GPS time tracks UTC (0: best guess)")
QT_TRANSLATE_NOOP("core","GPS week rollover period we're in (-1: best guess)")
QT_TRANSLATE_NOOP("core","SkyTraq Venus based loggers (download)")
QT_TRANSLATE_NOOP("core","First sector to be read from the file")
QT_TRANSLATE_NOOP("core","Last sector to be read from the file (-1: read till empty sector)")
QT_TRANSLATE_NOOP("core","Seconds that GPS time tracks UTC (0: best guess)")
QT_TRANSLATE_NOOP("core","GPS week rollover period we're in (-1: best guess)")
QT_TRANSLATE_NOOP("core","SkyTraq Venus based loggers Binary File Format")
QT_TRANSLATE_NOOP("core","Video position for which exact GPS time is known (hhmmss, default is 0:00:00)")
QT_TRANSLATE_NOOP("core","GPS time at position video_time (hhmmss, default is first timestamp of track)")
QT_TRANSLATE_NOOP("core","GPS date at position video_time (hhmmss, default is first timestamp of track)")
QT_TRANSLATE_NOOP("core","Format for subtitles")
QT_TRANSLATE_NOOP("core","SubRip subtitles for video mapping (.srt)")
QT_TRANSLATE_NOOP("core","Index of route (if more than one in source)")
QT_TRANSLATE_NOOP("core","Suunto Trek Manager (STM) .sdf files")
QT_TRANSLATE_NOOP("core","Index of route/track to write (if more than one in source)")
QT_TRANSLATE_NOOP("core","Suunto Trek Manager (STM) WaypointPlus files")
QT_TRANSLATE_NOOP("core","Swiss Map 25/50/100 (.xol)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Tab delimited fields useful for OpenOffice")
QT_TRANSLATE_NOOP("core","Teletype [ Get Jonathon Johnson to describe")
QT_TRANSLATE_NOOP("core","Suppress separator lines between waypoints")
QT_TRANSLATE_NOOP("core","Encrypt hints using ROT13")
QT_TRANSLATE_NOOP("core","Include groundspeak logs if present")
QT_TRANSLATE_NOOP("core","Degrees output as 'ddd', 'dmm'(default) or 'dms'")
QT_TRANSLATE_NOOP("core","Units for altitude (f)eet or (m)etres")
QT_TRANSLATE_NOOP("core","Write each waypoint in a separate file")
QT_TRANSLATE_NOOP("core","Textual Output")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","TomTom Itineraries (.itn)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","TomTom Places Itineraries (.itn)")
QT_TRANSLATE_NOOP("core","Max synthesized shortname length")
QT_TRANSLATE_NOOP("core","Allow whitespace synth. shortnames")
QT_TRANSLATE_NOOP("core","UPPERCASE synth. shortnames")
QT_TRANSLATE_NOOP("core","Make synth. shortnames unique")
QT_TRANSLATE_NOOP("core","Basename prepended to URL on output")
QT_TRANSLATE_NOOP("core","Use shortname instead of description")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","TomTom POI file (.asc)")
QT_TRANSLATE_NOOP("core","TomTom POI file (.ov2)")
QT_TRANSLATE_NOOP("core","TopoMapPro Places File")
QT_TRANSLATE_NOOP("core","Index of track (if more than one in source)")
QT_TRANSLATE_NOOP("core","TrackLogs digital mapping (.trl)")
QT_TRANSLATE_NOOP("core","Suppress labels on generated pins")
QT_TRANSLATE_NOOP("core","Generate file with lat/lon for centering map")
QT_TRANSLATE_NOOP("core","Margin for map.  Degrees or percentage")
QT_TRANSLATE_NOOP("core","Max shortname length when used with -s")
QT_TRANSLATE_NOOP("core","Days after which points are considered old")
QT_TRANSLATE_NOOP("core","Marker type for old points")
QT_TRANSLATE_NOOP("core","Marker type for new points")
QT_TRANSLATE_NOOP("core","Suppress whitespace in generated shortnames")
QT_TRANSLATE_NOOP("core","Marker type for unfound points")
QT_TRANSLATE_NOOP("core","Width in pixels of map")
QT_TRANSLATE_NOOP("core","Height in pixels of map")
QT_TRANSLATE_NOOP("core","The icon description is already the marker")
QT_TRANSLATE_NOOP("core","U.S. Census Bureau Tiger Mapping Service")
QT_TRANSLATE_NOOP("core","GPS datum (def. WGS 84)")
QT_TRANSLATE_NOOP("core","Write position using this grid.")
QT_TRANSLATE_NOOP("core","Write timestamps with offset x to UTC time")
QT_TRANSLATE_NOOP("core","Write name(s) of format(s) from input session(s)")
QT_TRANSLATE_NOOP("core","Write filename(s) from input session(s)")
QT_TRANSLATE_NOOP("core","Universal csv with field structure in first line")
QT_TRANSLATE_NOOP("core","Encrypt hints using ROT13")
QT_TRANSLATE_NOOP("core","Vcard Output (for iPod)")
QT_TRANSLATE_NOOP("core","Version of VidaOne file to read or write (1 or 2)")
QT_TRANSLATE_NOOP("core","VidaOne GPS for Pocket PC (.gpb)")
QT_TRANSLATE_NOOP("core","Vito Navigator II tracks")
QT_TRANSLATE_NOOP("core","Vito SmartMap tracks (.vtt)")
QT_TRANSLATE_NOOP("core","Infrastructure closed icon name")
QT_TRANSLATE_NOOP("core","Infrastructure open icon name")
QT_TRANSLATE_NOOP("core","Ad-hoc closed icon name")
QT_TRANSLATE_NOOP("core","Ad-hoc open icon name")
QT_TRANSLATE_NOOP("core","Shortname is MAC address")
QT_TRANSLATE_NOOP("core","WiFiFoFum 2.0 for PocketPC XML")
QT_TRANSLATE_NOOP("core","Wintec TES file")
QT_TRANSLATE_NOOP("core","Wintec WBT-100/200 Binary File Format")
QT_TRANSLATE_NOOP("core","Erase device data after download")
QT_TRANSLATE_NOOP("core","Wintec WBT-100/200 GPS Download")
QT_TRANSLATE_NOOP("core","Wintec WBT-201/G-Rays 2 Binary File Format")
QT_TRANSLATE_NOOP("core","Appends the input to a backup file")
QT_TRANSLATE_NOOP("core","Only waypoints that are not the backup file")
QT_TRANSLATE_NOOP("core","XAiOX iTrackU Logger")
QT_TRANSLATE_NOOP("core","Appends the input to a backup file")
QT_TRANSLATE_NOOP("core","Only waypoints that are not the backup file")
QT_TRANSLATE_NOOP("core","XAiOX iTrackU Logger Binary File Format")
QT_TRANSLATE_NOOP("core","String to separate concatenated address fields (default=\", \")")
QT_TRANSLATE_NOOP("core","Yahoo Geocode API data")
