# this file is used to build the image gpsbabel_build_environment used by travis.

FROM ubuntu:jammy AS stage

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# install packages needed for gpsbabel build
# split into multiple commands to limit layer size

# basic build and test tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    autoconf \
    git \
    expat \
    libxml2-utils \
    cmake \
    ninja-build \
    curl \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# pkgs with libraries needed by gpsbabel
RUN apt-get update && apt-get install -y --no-install-recommends \
    libusb-1.0-0-dev \
    pkg-config \
    libudev-dev \
    libshp-dev \
    zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

# pkgs with qt used by gpsbabel
RUN apt-get update && apt-get install -y --no-install-recommends \
    qtbase5-dev \
    qttools5-dev \
    qttools5-dev-tools \
    qttranslations5-l10n \
    qtwebengine5-dev \
    libqt5serialport5-dev \
 && rm -rf /var/lib/apt/lists/*

# install environment for locale test
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
 && rm -rf /var/lib/apt/lists/* \
 && sed -i 's/^# *\(en_US ISO-8859-1\)/\1/' /etc/locale.gen \
 && locale-gen \
 && locale -a

RUN --mount=type=bind,target=/home/gpsbabel/gpsbabel-build,rw cd /home/gpsbabel/gpsbabel-build \
 && rm -fr zlib \
 && rm -fr shapelib \
 && sed -i -e"/GB.SHA/i set(ENV{GITHUB_SHA} \"$(git log -1 --format=%h)\")" gbversion.cmake \
 && qmake WITH_ZLIB=pkgconfig WITH_SHAPELIB=pkgconfig && make -j 10 unix-gui && make check \
 && mkdir -p /usr/local/cellar \
 && cp -pr gui/GPSBabelFE /usr/local/cellar \
 && ln -s /usr/local/cellar/GPSBabelFE/gpsbabel /usr/local/bin \
 && ln -s /usr/local/cellar/GPSBabelFE/gpsbabelfe /usr/local/bin \
 && cp tools/archive_images/setup_user.sh /usr/local/bin

FROM ubuntu:jammy

LABEL maintainer="https://github.com/tsteven4"

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# for hints 
# ubuntu jammy gpsbabel (1.8.0+ds-4) dependencies
# ubuntu jammy gpsbabel-gui (1.8.0+ds-4) dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libshp2 \
    libudev1 \
    libusb-1.0-0 \
    zlib1g \
    libqt5core5a \
    libqt5gui5 \
    libqt5network5 \
    libqt5serialport5 \
    libqt5webchannel5 \
    libqt5webenginewidgets5 \
    libqt5widgets5 \
    libqt5xml5 \
    qttranslations5-l10n \
 && rm -rf /var/lib/apt/lists/*

COPY --from=stage /usr/local/cellar /usr/local/cellar
COPY --from=stage /usr/local/bin/setup_user.sh /usr/local/bin

RUN ln -s /usr/local/cellar/GPSBabelFE/gpsbabel /usr/local/bin \
 && ln -s /usr/local/cellar/GPSBabelFE/gpsbabelfe /usr/local/bin

RUN useradd ubuntu -m -s /bin/bash
USER ubuntu:ubuntu
WORKDIR /app
