# this file is used to build the image gpsbabel_build_environment used by travis.

FROM fedora:35

LABEL maintainer="https://github.com/tsteven4"

WORKDIR /app

# basic tools to build
RUN dnf install --assumeyes git make valgrind diffutils findutils langpacks-en ninja-build && \
    dnf clean all
# libraries used by gpsbabel.  zlib and shapelib may or may not be used depending qmake options.
RUN dnf install --assumeyes libusb1-devel zlib-devel shapelib-devel && \
    dnf clean all
# Qt used by gpsbabel, gpsbabelfe
RUN dnf install --assumeyes qt5-qtbase-devel qt5-qtserialport-devel qt5-qtwebengine-devel qt5-linguist qt5-qttranslations && \
    dnf clean all
# tools to build the docs
RUN dnf install --assumeyes expat desktop-file-utils libxslt docbook-style-xsl fop docbook5-style-xsl && \
    dnf clean all

# no jing on f35...
RUN dnf install --assumeyes zip  && \
    dnf clean all && \
    mkdir /usr/local/opt && \
    cd /usr/local/opt && \
    curl -o jing.zip -L https://github.com/relaxng/jing-trang/releases/download/V20220510/jing-20220510.zip && \
    unzip jing.zip && \
    echo 'exec java -jar "/usr/local/opt/jing-20220510/bin/jing.jar" "$@"' >/usr/bin/jing && \
    chmod +x /usr/bin/jing
     
# create a link as fedora uses the name qmake-qt5 for Qt5's qmake.
RUN alternatives --install /usr/bin/qmake qt /usr/lib64/qt5/bin/qmake 100
