# this file is used to build the image gpsbabel_build_environment used by travis.

FROM ubuntu:noble AS clazy

# build our own clazy, ubuntu package is compromised (need c++17 to enable some checks, use Qt6)

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# install packages needed for gpsbabel build
# split into multiple commands to limit layer size

# basic build and test tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    git \
    cmake \
    ninja-build \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# pkgs with qt used by clazy test
RUN apt-get update && apt-get install -y --no-install-recommends \
    qtbase5-dev \
    qttools5-dev \
    qtdeclarative5-dev \
    libqt5svg5-dev \
    qtmultimedia5-dev \
    libqt5networkauth5-dev \
 && rm -rf /var/lib/apt/lists/*

# pkgs with qt used by clazy test
RUN apt-get update && apt-get install -y --no-install-recommends \
    qt6-base-dev \
    qt6-tools-dev \
   	qt6-declarative-dev \
    qt6-scxml-dev \
    qt6-networkauth-dev \
    qt6-svg-dev \
   	qt6-multimedia-dev \
 && rm -rf /var/lib/apt/lists/*

# some tests fail because qtmochelpers.h is missing, and one just fails
RUN apt-get update && apt-get install -y --no-install-recommends \
    llvm-dev libclang-dev clang-tools libclang-cpp-dev \
 && rm -rf /var/lib/apt/lists/* \
 && git clone https://github.com/KDE/clazy.git \
 && cd clazy \
 && git checkout v1.12 \
 && mkdir bld \
 && cd bld \
 && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17  -G Ninja .. \
 && cmake --build . \
 && cmake --build . --target install \
 && ctest -j 8 -E "detaching-temporary|fully-qualified-moc-types|old-style-connect"

FROM ubuntu:noble 
LABEL maintainer="https://github.com/tsteven4"

WORKDIR /app

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# install packages needed for gpsbabel build
# split into multiple commands to limit layer size

# basic build and test tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    git \
    valgrind \
    expat \
    libxml2-utils \
    bear \
    cmake \
    ninja-build \
    clang-tidy \
    jq \
    curl \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# alternative compiler
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
 && rm -rf /var/lib/apt/lists/*

# pkgs needed to build document
RUN apt-get update && apt-get install -y --no-install-recommends \
    fop \
    xsltproc \
    docbook-xml \
    docbook5-xml \
    docbook-xsl \
    docbook-xsl-ns \
    libavalon-framework-java \
    jing \
 && rm -rf /var/lib/apt/lists/*

# pkgs with libraries needed by gpsbabel
RUN apt-get update && apt-get install -y --no-install-recommends \
    libusb-1.0-0-dev \
    pkg-config \
    libudev-dev \
 && rm -rf /var/lib/apt/lists/*

# pkgs with qt used by gpsbabel
RUN apt-get update && apt-get install -y --no-install-recommends \
    qt6-base-dev \
    qt6-5compat-dev \
    qt6-serialport-dev \
    libx11-xcb-dev \
    libxkbcommon-dev \
    qt6-tools-dev \
    qt6-translations-l10n \
    qt6-webengine-dev \
    qt6-wayland \
 && rm -rf /var/lib/apt/lists/*

# dbgsyms for "libqt6core6t64/noble,now 6.4.2+dfsg-21.1build5 amd64" needed for gpsbabel.supp
RUN apt-get update && apt-get install -y --no-install-recommends ubuntu-dbgsym-keyring \
 && echo "deb http://ddebs.ubuntu.com noble main restricted universe multiverse" >> /etc/apt/sources.list.d/ddebs.list \
 && echo "deb http://ddebs.ubuntu.com noble-updates main restricted universe multiverse" >> /etc/apt/sources.list.d/ddebs.list \
 && echo "deb http://ddebs.ubuntu.com noble-proposed main restricted universe multiverse" >> /etc/apt/sources.list.d/ddebs.list \
 && apt-get update && apt-get install -y --no-install-recommends libqt6core6t64-dbgsym \
 && rm -rf /var/lib/apt/lists/*

# pkgs needed to generate coverage report:
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcovr \
 && rm -rf /var/lib/apt/lists/*

# install environment for locale test
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
 && rm -rf /var/lib/apt/lists/* \
 && sed -i 's/^# *\(en_US ISO-8859-1\)/\1/' /etc/locale.gen \
 && locale-gen \
 && locale -a

COPY --from=clazy /usr/local/ /usr/local/

