#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
# Note the script must be sourced if you want the modified PATH to
# be used outside this script.
#

# our expectation is that qt-5.9.5-osx creates $QTDIR, $QTDIR/bin.
QTDIR=${HOME}/Qt/5.9.5/clang_64

if [ -d "${QTDIR}/bin" ]; then
  echo "Using cached Qt."
  echo "If you need to clear the cache see"
  echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
else
  pushd ${HOME};
  rm -fr Qt
  # qt-5.9.5-osx creates the install at $PWD/Qt.
  QT_CI_PACKAGES=qt.595.clang_64,qt.595.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} qt-5.9.5-osx;
  popd;
fi
# note that qt-5.9.5-osx.env created by qt-5.9.5-osx is not cached!
export PATH=${QTDIR}/bin:${PATH}
unset -v QTDIR
