#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
#

QT_VERSION=${1:-5.12.0}
QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')

# our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
CACHEDIR=${HOME}/Cache
QTDIR=${CACHEDIR}/Qt/${QT_VERSION}/gcc_64

if [ -d "${QTDIR}/bin" ]; then
  echo "Using cached Qt."
  echo "If you need to clear the cache see"
  echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
else
  rm -fr ${CACHEDIR}
  mkdir -p ${CACHEDIR}
  pushd ${CACHEDIR}
  # install-qt creates the install at $PWD/Qt.
  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.gcc_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
  popd;
  if [ ! -e ${QTDIR}/bin/qmake ]; then
    echo "ERROR: qmake not found on the installation path." >&2
    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
    find ${CACHEDIR}/Qt -maxdepth 3
    cat ${CACHEDIR}/Qt/InstallationLog.txt
    cat ${CACHEDIR}/Qt/components.xml
    exit 1
  fi
fi

# prepare locale for test_encoding_latin1, requires locales package.
sudo rm -rf /var/lib/apt/lists/* \
  && sudo sed -i 's/^# *\(en_US ISO-8859-1\)/\1/' /etc/locale.gen \
  && sudo locale-gen \
  && locale -a
