#!/bin/bash -e

# dont leak unhashed tokens!
set +x
if [ ! -z "${CODACY_PROJECT_TOKEN+x}" ] ; then
  if which sha512sum; then
    echo -n "CODACY_PROJECT_TOKEN hash: "
    echo $CODACY_PROJECT_TOKEN | sha512sum
  else
    echo CODACY_PROJECT_TOKEN hash unknown.
  fi
else
  echo CODACY_PROJECT_TOKEN not set.
fi
if [ ! -z "${GITHUB_TOKEN+x}" ] ; then
  if which sha512sum; then
    echo -n "GITHUB_TOKEN hash: "
    echo $GITHUB_TOKEN | sha512sum
  else
    echo GITHUB_TOKEN hash unknown.
  fi
else
  echo GITHUB_TOKEN not set.
fi
set -x
