#!/bin/sh
# Extract XPaths from an XML document

set -e
if test -z "$2" || test -n "$4"; then
	echo "Usage: $0 xpath xmlfile"
  exit 1
fi

xpath="$1"
xmlfile="$2"

# xmllint makes it really inconvienent to work with namespaces. you can
# set namespace aliases in shell, but as soon as you use the shell, xmllint
# starts giving you very un-xml-like output, especially for the result of
# functions like count().
sed -E -e 's,xmlns="[^"]+",,' "$xmlfile" | xmllint --xpath "$xpath" -
