name: gpsbabel # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
summary: "Convert, manipulate and transfer GPS data."
description: |
  Convert, manipulate and transfer data from GPS programs or GPS
  recievers.  Open source and supported on macOS, Windows and Linux.

license: GPL-2.0
title: GPSBabel
source-code: https://github.com/GPSBabel/gpsbabel.git
website: https://www.gpsbabel.org

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  gpsbabel:
    extensions: [gnome]
    plugs:
      - home
      - raw-usb
      - removable-media
      - serial-port
    command: usr/bin/gpsbabel
  gpsbabelfe:
#   avoid issues with fonts replaced by empty squares
#   avoid issue: pxbackend-WARNING **: 08:18:06.724: GNOME desktop detected but no schemes installed, aborting.
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - network-status
      - home
      - removable-media
      - network
      - opengl
      - unity7
      - wayland
      - x11
    command-chain:
      - usr/bin/gpsbabelfe.sh
    command: usr/bin/gpsbabelfe
    environment:
#      QT_DEBUG_PLUGINS: 1
#     bug https://forum.snapcraft.io/t/libpxbackend-1-0-so-cannot-open-shared-object-file-no-such-file-or-directory/44263
#     error while loading shared libraries: libpxbackend-1.0.so: cannot open shared object file: No such file or directory
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy

plugs:
# avoid FATAL:credentials.cc(122)] Check failed: . : Permission denied (13) with map preview
# requires manual connection
  browser-sandbox: # gpsbabelfe
    interface: browser-support
    allow-sandbox: true

# remap the ubuntu qt6 install directories to the snap.
layout:
  /usr/share/qt6:
    symlink: $SNAP/usr/share/qt6
  /usr/lib/qt6:
    symlink: $SNAP/usr/lib/qt6
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6
# XKB_CONFIG_ROOT, QT_XKB_CONFIG_ROOT not enough to prevent "xkbcommon: ERROR: Couldn't find file "rules/evdev" in include paths"
# to overcome this symlink /usr/share/X11/xkb
# see https://bugreports.qt.io/browse/QTBUG-105124
# supposedly fixed in Qt 6.5.
  /usr/share/X11/xkb:
    symlink: $SNAP/gnome-platform/usr/share/X11/xkb

adopt-info: gpsbabel
parts:
  gpsbabel:
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DGPSBABEL_WITH_ZLIB=pkgconfig
      - -DGPSBABEL_WITH_SHAPELIB=pkgconfig
    cmake-generator: Ninja
    source: .
    override-pull: |
      craftctl default
      # add install command to CMakeLists.txt
      echo "install(TARGETS gpsbabel gpsbabelfe CONFIGURATIONS Release RUNTIME DESTINATION /usr/bin)" >> CMakeLists.txt
      echo "install(PROGRAMS snap/local/gpsbabelfe.sh DESTINATION /usr/bin)" >> CMakeLists.txt
      # jam repo sha into GITHUB_SHA
      sed -i -e"/GB.SHA/i set(ENV{GITHUB_SHA} \"$(git log -1 --format=%h)\")" gbversion.cmake
      # set snap version
      # ensure version has at most 32 characters
      craftctl set version="$(git describe | sed -e 's/gpsbabel_//' -e 's/_/./g')"
    build-packages:
      - git
      - vim
      - g++
      - ninja-build
      - zlib1g-dev
      - libshp-dev
      - libusb-1.0-0-dev
      - pkg-config
      - libudev-dev
      - qt6-base-dev
      - qt6-5compat-dev
      - qt6-serialport-dev
      - libx11-xcb-dev
      - libxkbcommon-dev
      - qt6-tools-dev
      - qt6-translations-l10n
      - qt6-webengine-dev
      - qt6-wayland

    stage-packages:
      - zlib1g
      - libshp4
      - libusb-1.0-0
      - libqt6core6
      - libqt6core5compat6
      - libqt6gui6
      - libqt6network6
      - libqt6serialport6
      - libqt6widgets6
      - libqt6xml6
      - libqt6webenginewidgets6
      - libqt6webenginecore6
      - libqt6webenginecore6-bin
      - qt6-translations-l10n
      - qt6-qpa-plugins
      - qt6-wayland

  gpu-2404:
    after: [gpsbabel]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper

  cleanup:
    after:
      - gpsbabel
      - gpu-2404
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core24
      - gnome-46-2404 
      - mesa-2404 
    override-prime: |
      set -eux
      for snap in "core24" "gnome-46-2404" "mesa-2404"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done

lint:
  ignore:
    - library:
#     these are all required by libQt6WebEngineCore.so.6.4.2
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz-subset.so.0.*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz.so.0.*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpsl.so.5.*
