#!/bin/sh

#
# delete all files listed in .cvsignore
#

find . -type d | 
while read dirname; do
	test -s "$dirname/.cvsignore" || continue
	while read filemask; do
		test -z "$filemask" && continue
		cmd="rm -fv $dirname/$filemask"
		${cmd}
	done < "$dirname/.cvsignore"
done
