name: "build docker archive"
permissions: {}

on: 
  workflow_call:
    inputs:
      version:
        description: 'verison to archive'
        required: false
        default: dev
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'verison to archive'
        required: true
        type: string

jobs:
  docker:
    name: docker Build
    runs-on: ubuntu-latest
    env:
      docker_repository: tsteven4/testing
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: tsteven4
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and export to Docker
      uses: docker/build-push-action@v7
      with:
        context: "{{defaultContext}}:tools/archive_images"
        file: "Dockerfile_gpsbabel_${{ inputs.version }}"
        load: true
        tags: "${{ env.docker_repository }}:test_${{ inputs.version }}"
    - name: Test
      run: |
        # tests failed before 1.6.0 (and repository structure was different)
        if [[ "${{ inputs.version }}" == "dev" || $(echo -e "${{ inputs.version }}\n1.6.0" | sort -V | head -n1) == "1.6.0" ]]; then
          container=$(docker create -q -i -t -w /app -v "$(pwd):/app" "${{ env.docker_repository }}:test_${{ inputs.version }}")
          trap 'docker rm -f "${container}" >/dev/null' 0 1 2 3 15
          docker start "${container}" >/dev/null
          docker exec "${container}" setup_user.sh "$(id -u)" "$(id -g)"
          docker exec -u "$(id -u):$(id -g)" -w /home/gpsbabel/gpsbabel-build -e PNAME=/usr/local/bin/gpsbabel "${container}" ./testo
        fi
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: "{{defaultContext}}:tools/archive_images"
        file: "Dockerfile_gpsbabel_${{ inputs.version }}"
        push: true
        tags: "${{ env.docker_repository }}:${{ inputs.version }}"
