name: "docker"
permissions: {}

on:
  push:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  docker:
    name: docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: tsteven4
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:tools/archive_images"
        file: Dockerfile_gpsbabel_dev
        load: true
        tags: tsteven4/gpsbabel:test_dev
    - name: Test
      run: |
        container=$(docker create -q -i -t -w /app -v "$(pwd):/app" "tsteven4/gpsbabel:test_dev")
        trap 'docker rm -f "${container}" >/dev/null' 0 1 2 3 15
        docker start "${container}" >/dev/null
        docker exec "${container}" setup_user.sh "$(id -u)" "$(id -g)"
        docker exec -u "$(id -u):$(id -g)" -w /home/gpsbabel/gpsbabel-build "${container}" ./testo -p /usr/local/bin/gpsbabel
    - name: Build and push
      if: ( github.event_name == 'push' ) && ( github.ref == 'refs/heads/master' )
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:tools/archive_images"
        file: Dockerfile_gpsbabel_dev
        push: true
        tags: tsteven4/gpsbabel:dev
