name: build docker archives
permissions: {}

on:
  workflow_dispatch: ~

jobs:
  rebuild_all_archives:
    name: build docker archives
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.5.0
            latest: false
          - version: 1.5.1
            latest: false
          - version: 1.5.2
            latest: false
          - version: 1.5.3
            latest: false
          - version: 1.5.4
            latest: false
          - version: 1.6.0
            latest: false
          - version: 1.7.0
            latest: false
          - version: 1.8.0
            latest: false
          - version: 1.9.0
            latest: false
          - version: 1.10.0
            latest: true

    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ matrix.version }}
      latest: ${{ matrix.latest }}
    secrets: inherit
